/*kredencijali za placanje
username:  sb-qq2m924846107@personal.example.com
password:  n?I7/iR2
 */

insert into Role (name)
VALUES ('ROLE_ADMIN');/*1*/
insert into Role (name)
VALUES ('ROLE_CUSTOMER');/*2*/
insert into Role (name)
VALUES ('ROLE_USER');

insert into user_auth(deleted, is_enabled, last_password_set, verification_code)
values (false, true, '2021-12-12', null),
       (false, true, '2021-12-12', null),
       (false, true, '2021-12-12', null),
       (false, true, '2021-12-12', null),
       (false, true, '2021-12-12', null),
       (false, true, '2021-12-12', null),
       (false, true, '2021-12-12', null),
       (false, true, '2021-12-12', null);

insert into admin (email, city, deleted, blocked, name, password, phone_number, role, surname, user_auth_id)
values ('admin@gmail.com', 'Adminville', false, false, 'Admin',
        '$2a$10$tnplXdStY6t7kOqqKssMYedAGjJ0T3OJH2BxeT81c1YrDqOUvHLD6', '064 123456', 0, 'Adminic', 1),
       ('admin111@gmail.com', 'Adminville', false, false, 'Admin',
        '$2a$10$tnplXdStY6t7kOqqKssMYedAGjJ0T3OJH2BxeT81c1YrDqOUvHLD6', '064 123456', 0, 'Adminic', 2);

insert into user_auth_roles(user_auth_id, roles_id)
values (1, 1),
       (1, 3),
       (2, 1),
       (2, 3);

insert into customer (email, city, deleted, blocked, name, password, phone_number, role, surname, user_auth_id,
                      number_of_tokens, is_active)
values ('customer@gmail.com', 'Customville', false, false, 'Customer',
        '$2a$10$2Mtev/q1qqNoSn39O7194eZVLBEvgM2dKzjkO0NUWETNKUYY9R/RO', '064 433456', 2, 'Customic', 6, 1000.0, false),
       ('petar@gmail.com', 'Petrovgrad', false, false, 'Petar',
        '$2a$10$tnplXdStY6t7kOqqKssMYedAGjJ0T3OJH2BxeT81c1YrDqOUvHLD6', '064 654321', 2, 'Petrovic', 7, 11150.0, false);

insert into user_auth_roles(user_auth_id, roles_id)
values (3, 2),
       (3, 3),
       (4, 2),
       (4, 3);

INSERT INTO Hotel (name, address, city, country, rating, stars, image_url, distance_from_center)
values ('Italian Villa', '123 Via Roma', 'Rome', 'Italy', 8.7, 5,
        'https://images.unsplash.com/photo-1594741158704-5a784b8e59fb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
        500),
       ('Coastal Retreat', '456 Via Marina', 'Sorrento', 'Italy', 9.2, 4,
        'https://images.unsplash.com/photo-1588284722618-55732cfed6b3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
        200),
       ('Tuscan Resort', '789 Via Toscana', 'Florence', 'Italy', 8.5, 4,
        'https://images.unsplash.com/photo-1609949279531-cf48d64bed89?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
        1000),
       ('Venetian Palace', '321 Piazza San Marco', 'Venice', 'Italy', 9.8, 5,
        'https://images.unsplash.com/photo-1535825400335-401dbaeea8d2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1171&q=80',
        300),
       ('Amalfi Coast Resort', '987 Via Positano', 'Amalfi', 'Italy', 8.3, 3,
        'https://images.unsplash.com/photo-1528301719638-3f517aebc11c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
        100),
       ('Beachfront Hotel', '123 Beach Road', 'Athens', 'Greece', 8.7, 5,
        'https://images.unsplash.com/photo-1582757345040-9e0d1ebbeefb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1032&q=80',
        100),
       ('Island Paradise', '456 Paradise Island', 'Mykonos', 'Greece', 9.2, 4,
        'https://images.unsplash.com/photo-1498503403619-e39e4ff390fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bXlrb25vcyUyMGhvdGVsfGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60',
        0),
       ('Santorini Retreat', '789 Caldera Cliff', 'Santorini', 'Greece', 8.5, 4,
        'https://images.unsplash.com/photo-1586595847028-8f459a1e58a8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1240&q=80',
        100),
       ('Crete Resort', '321 Elafonisi Beach', 'Crete', 'Greece', 9.8, 5,
        'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y3JldGUlMjBob3RlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=600&q=60',
        200),
       ('Rhodes Beach Hotel', '987 Rhodes Town', 'Rhodes', 'Greece', 8.3, 3,
        'https://images.unsplash.com/photo-1671173832142-d4b1ac622b4d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cm9kb3MlMjBob3RlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=600&q=60',
        50),
       ('Bosphorus View Hotel', '123 Bosphorus Ave', 'Istanbul', 'Turkey', 8.7, 5,
        'https://images.unsplash.com/photo-1675409145919-277c0fc2aa7d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
        500),
       ('Antalya Beach Resort', '456 Lara Beach', 'Antalya', 'Turkey', 9.2, 4,
        'https://images.unsplash.com/photo-1677177906706-c2b597d9e8e0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGFudGFseWElMjBob3RlbHxlbnwwfDB8MHx8fDA%3D&auto=format&fit=crop&w=600&q=60',
        0),
       ('Cappadocia Cave Hotel', '789 Fairy Chimneys St', 'Cappadocia', 'Turkey', 8.5, 4,
        'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FwY2Fkb2NpYSUyMGhvdGVsfGVufDB8MHwwfHx8MA%3D%3D&auto=format&fit=crop&w=600&q=60',
        2000),
       ('Pamukkale Thermal Resort', '321 Hierapolis Ave', 'Pamukkale', 'Turkey', 9.8, 5,
        'https://images.unsplash.com/photo-1529290130-4ca3753253ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1176&q=80',
        100),
       ('Bodrum Beachfront Hotel', '987 Bodrum Peninsula', 'Bodrum', 'Turkey', 8.3, 3,
        'https://images.unsplash.com/photo-1597390871277-666712598c1d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1215&q=80',
        100);

INSERT INTO Review (id, rating, comment, posted)
values (1, 9, 'Great hotel with beautiful views!', '2023-05-01'),
       (2, 8, 'Comfortable stay, friendly staff.', '2023-05-02'),
       (3, 9, 'Lovely accommodations and excellent service.', '2023-05-03'),
       (4, 9, 'Perfect beachfront location!', '2023-05-04'),
       (5, 7, 'Nice hotel, but could use some improvements.', '2023-05-05'),
       (6, 10, 'Absolutely stunning views and top-notch service.', '2023-05-06'),
       (7, 8, 'Good hotel for a relaxing getaway.', '2023-05-07'),
       (8, 9, 'Highly recommended, great facilities.', '2023-05-08'),
       (9, 7, 'Decent hotel, but not exceptional.', '2023-05-09');

-- INSERT INTO Hotel_Review (hotel_id, review_id)
-- VALUES (1, 1),
--        (2, 2),
--        (3, 3),
--        (4, 4),
--        (5, 5),
--        (6, 6),
--        (7, 7),
--        (8, 8),
--        (9, 9);


INSERT INTO AIRPORT(CODE, COUNTRY, NAME)
VALUES ('AAR', 'Denmark', 'Aarhus'),
('ABD', 'Iran', 'Abadan'),
('AEH', 'Chad', 'Abeche'),
('ABZ', 'United Kingdom', 'Aberdeen'),
('ABR', 'USA', 'Aberdeen (SD)'),
('ABJ', 'Cote d Ivoire', 'Abidjan'),
('ABI', 'USA', 'Abilene (TX)'),
('AUH', 'United Arab Emirates', 'Abu Dhabi - Abu Dhabi International'),
('ABV', 'Nigeria', 'Abuja - Nnamdi Azikiwe International Airport'),
('AUE', 'Egypt', 'Abu Rudeis'),
('ABS', 'Egypt', 'Abu Simbel'),
('ACA', 'Mexico', 'Acapulco'),
('ACC', 'Ghana', 'Accra - Kotoka International Airport'),
('ADA', 'Turkey', 'Adana'),
('ADD', 'Ethiopia', 'Addis Ababa - Bole International Airport'),
('ADL', 'Australia', 'Adelaide'),
('ADE', 'Yemen', 'Aden - Aden International Airport'),
('ADF', 'Turkey', 'Adiyaman'),
('AER', 'Russia', 'Adler/Sochi'),
('AJY', 'Niger', 'Agades'),
('AGA', 'Morocco', 'Agadir'),
('SUM', 'Guam', 'Agana (Hagåtña)'),
('AGZ', 'South Africa', 'Aggeneys'),
('BQN', 'Puerto Rico', 'Aguadilla'),
('AGU', 'Mexico', 'Aguascaliente'),
('AMD', 'India', 'Ahmedabad'),
('AYU', 'Papua New Guinea', 'Aiyura'),
('AJA', 'France', 'Ajaccio'),
('AXT', 'Japan', 'Akita'),
('CAK', 'USA', 'Akron (OH)'),
('AKT', 'Cyprus', 'Akrotiri - RAF'),
('AAN', 'United Arab Emirates', 'Al Ain'),
('AAC', 'Egypt', 'Al Arish'),
('ALH', 'Australia', 'Albany'),
('ABY', 'USA', 'Albany (GA)'),
('ALB', 'USA', 'Albany (NY) - Albany International Airport'),
('LBI', 'France', 'Albi'),
('AAL', 'Denmark', 'Alborg'),
('ABQ', 'USA', 'Albuquerque (NM)'),
('ABX', 'Australia', 'Albury'),
('ACI', 'Channel Islands', 'Alderney'),
('ALP', 'Syria', 'Aleppo'),
('AES', 'Norway', 'Alesund'),
('ALJ', 'South Africa', 'Alexander Bay - Kortdoorn'),
('HBH', 'Egypt', 'Alexandria - Borg el Arab Airport'),
('ALY', 'Egypt', 'Alexandria - El Nhouza Airport'),
('ESF', 'USA (LA)', 'Alexandria - Esler Field'),
('FJR', 'United Arab Emirates', 'Alfujairah (Fujairah)'),
('AHO', 'Italy', 'Alghero Sassari'),
('ALG', 'Algeria', 'Algiers, Houari Boumediene Airport'),
('AHU', 'Morocco', 'Al Hoceima'),
('ALC', 'Spain', 'Alicante'),
('ASP', 'Australia', 'Alice Springs'),
('ADY', 'South Africa', 'Alldays'),
('ABE', 'USA', 'Allentown (PA)'),
('ALA', 'Kazakhstan', 'Almaty (Alma Ata) - Almaty International Airport'),
('LEI', 'Spain', 'Almeria'),
('ALF', 'Norway', 'Alta'),
('AAT', 'PR China', 'Altay'),
('ACH', 'Switzerland', 'Altenrhein'),
('AOO', 'USA', 'Altoona (PA)'),
('AXS', 'USA', 'Altus'),
('ASJ', 'Japan', 'Amami'),
('AMA', 'USA', 'Amarillo (TX)'),
('AZB', 'Papua New Guinea', 'Amazon Bay'),
('AMM', 'Jordan', 'Amman - Queen Alia International Airport'),
('ADJ', 'Jordan', 'Amman - Amman-Marka International Airport'),
('ATQ', 'India', 'Amritsar'),
('AMS', 'Netherlands', 'Amsterdam - Amsterdam Airport Schiphol'),
('QNB', 'India', 'Anand'),
('ANC', 'USA', 'Anchorage (AK) - Ted Stevens Anchorage International'),
('AOI', 'Italy', 'Ancona - Ancona Falconara Airport'),
('ALV', 'Andorra', 'Andorra La Vella - Heliport'),
('AXA', 'Anguilla', 'Anguilla'),
('AJN', 'Comoros (Comores)', 'Anjouan - Anjouan Airport'),
('ANK', 'Turkey', 'Ankara'),
('ESB', 'Turkey', 'Ankara - Esenboğa International Airport'),
('AAE', 'Algeria', 'Annaba'),
('ARB', 'USA', 'Ann Arbor (MI)'),
('NCY', 'France', 'Annecy'),
('ANB', 'USA', 'Anniston (AL)'),
('AYT', 'Turkey', 'Antalya'),
('TNR', 'Madagascar', 'Antananarivo (Tanannarive) - Ivato International Airport'),
('ANU', 'Antigua and Barbuda', 'Antigua, V.C. Bird International'),
('ANR', 'Belgium', 'Antwerp'),
('AOJ', 'Japan', 'Aomori'),
('APW', 'Samoa', 'Apia - Faleolo International Airport'),
('ATW', 'USA', 'Appelton/Neenah/Menasha (WI)'),
('AQJ', 'Jordan', 'Aqaba'),
('AJU', 'Brazil', 'Aracaju'),
('ARH', 'Russia', 'Arkhangelsk'),
('ARK', 'Tanzania', 'Arusha'),
('GPA', 'Greece', 'Araxos'),
('RLT', 'Niger', 'Arlit'),
('ACE', 'Spain', 'Arrecife/Lanzarote'),
('AUA', 'Aruba', 'Aruba - Reina Beatrix International, Oranjestad'),
('AVL', 'USA', 'Asheville (NC)'),
('ASB', 'Turkmenistan', 'Ashgabat - Saparmurat Turkmenbashy Int. Airport'),
('ASM', 'Eritrea', 'Asmara - Asmara International'),
('ASE', 'USA', 'Aspen, (CO) - Aspen-Pitkin County Airport'),
('ATZ', 'Egypt', 'Assiut'),
('TSE', 'Kazakhstan', 'Astana - Astana International Airport'),
('ASU', 'Paraguay', 'Asuncion - Asunción International Airport'),
('ASW', 'Egypt', 'Aswan - Daraw Airport'),
('ATH', 'Greece', 'Athens - Elefthérios Venizélos International Airport'),
('HEW', 'Greece', 'Athens, Hellinikon Airport'),
('AHN', 'USA', 'Athens (GA)'),
('ATO', 'USA', 'Athens (OH)'),
('ATL', 'USA', 'Atlanta (GA) - Hartsfield Atlanta International Airport'),
('ACY', 'USA', 'Atlantic City (NJ) - Atlantic City International'),
('YAT', 'Canada', 'Attawapiskat, NT'),
('AKL', 'New Zealand', 'Auckland - Auckland International Airport'),
('AGB', 'Germany', 'Augsburg - Augsbur gAirport'),
('AGS', 'USA', 'Augusta (GA)'),
('AUG', 'USA', 'Augusta (ME) - Augusta State Airport'),
('AUR', 'France', 'Aurillac'),
('AUS', 'USA', 'Austin (TX) - Austin-Bergstrom Airport'),
('AYW', 'Indonesia', 'Ayawasi'),
('AYQ', 'Australia', 'Ayers Rock - Connellan'),
('AYR', 'Australia', 'Ayr'),
('BJZ', 'Spain', 'Badajoz'),
('BGW', 'Iraq', 'Bagdad - Baghdad International Airport'),
('IXB', 'India', 'Bagdogra'),
('NAS', 'The Bahamas', 'Bahamas - Lynden Pindling International Airport'),
('BHV', 'Pakistan', 'Bahawalpur'),
('BAH', 'Bahrain', 'Bahrain - Bahrain International Airport'),
('BFL', 'USA', 'Bakersfield (CA)'),
('BAK', 'Azerbaijan', 'Baku - Heydar Aliyev International Airport'),
('BNK', 'Australia', 'Ballina'),
('BWI', 'USA', 'Baltimore (MD) - Washington International Airport'),
('ABM', 'Australia', 'Bamaga'),
('BKO', 'Mali', 'Bamako - Bamako-Sénou International Airport'),
('BBY', 'Central African Republic', 'Bambari'),
('BWN', 'Brunei', 'Bandar Seri Begawan - Brunei International Airport'),
('BDO', 'Indonesia', 'Bandung - Husein Sastranegara International Airport'),
('BLR', 'India', 'Bangalore'),
('BGU', 'Central African Republic', 'Bangassou'),
('DMK', 'Thailand', 'Bangkok, Don Muang'),
('BKK', 'Thailand', 'Bangkok, Suvarnabhumi International'),
('BGR', 'USA', 'Bangor (ME)'),
('BGF', 'Central African Republic', 'Bangui - M Poko International Airport'),
('BJL', 'Gambia', 'Banjul - Banjul International Airport (Yundum International)'),
('BNP', 'Pakistan', 'Bannu'),
('BCN', 'Spain', 'Barcelona'),
('BLA', 'Venezuela', 'Barcelona'),
('BDU', 'Norway', 'Bardufoss'),
('BRI', 'Italy', 'Bari'),
('BZL', 'Bangladesh', 'Barisal'),
('BDQ', 'India', 'Baroda'),
('BRR', 'United Kingdom', 'Barra (the famous tidal beach landing)'),
('BAQ', 'Colombia', 'Barranquilla'),
('BSL', 'Switzerland', 'Basel'),
('EAP', 'Switzerland/France', 'Basel/Mulhouse'),
('BSR', 'Iraq', 'Basra, Basrah'),
('PTP', 'Guadeloupe', 'Basse-Terre - Pointe-à-Pitre International Airport'),
('SKB', 'Saint Kitts and Nevis', 'Basseterre - Robert L. Bradshaw International Airport'),
('BIA', 'France', 'Bastia'),
('BTR', 'USA', 'Baton Rouge (LA) - Baton Rouge Metropolitan Airport'),
('BYU', 'Germany', 'Bayreuth - Bindlacher-Berg'),
('BPT', 'USA', 'Beaumont/Pt. Arthur (TX)'),
('BKW', 'USA', 'Beckley (WV)'),
('EIS', 'Virgin Islands (British)', 'Beef Island - Terrance B. Lettsome'),
('PEK', 'China', 'Beijing'),
('NAY', 'China', 'Beijing - Nanyuan Airport'),
('BEW', 'Mozambique', 'Beira'),
('BEY', 'Lebanon', 'Beirut - Beirut Rafic Hariri International Airport'),
('BEL', 'Brazil', 'Belem - Val de Cans International Airport'),
('BHD', 'United Kingdom', 'Belfast - George Best Belfast City Airport'),
('BFS', 'United Kingdom', 'Belfast - Belfast International Airport'),
('IXG', 'India', 'Belgaum'),
('BEG', 'Serbia', 'Belgrad (Beograd) - Belgrade Nikola Tesla International'),
('BZE', 'Belize', 'Belize City - Philip S.W.Goldson International'),
('BLI', 'USA', 'Bellingham (WA)'),
('CNF', 'Brazil', 'Belo Horizonte - Tancredo Neves International Airport'),
('BJI', 'USA', 'Bemidji (MN)'),
('BEB', 'United Kingdom', 'Benbecula'),
('BEN', 'Libya', 'Benghazi (Bengasi)'),
('BUG', 'Angola', 'Benguela'),
('BEH', 'USA', 'Benton Harbour (MI)'),
('BBT', 'Central African Republic', 'Berberati'),
('BGY', 'Italy', 'Bergamo/Milan - Orio Al Serio'),
('BGO', 'Norway', 'Bergen'),
('EGC', 'France', 'Bergerac - Roumanieres'),
('BER', 'Germany', 'Berlin'),
('SXF', 'Germany', 'Berlin, Schoenefeld'),
('TXL', 'Germany', 'Berlin, Tegel'),
('THF', 'Germany', 'Berlin, Tempelhof (ceased operating in 2008)'),
('BDA', 'Bermuda', 'Bermuda - L.F. Wade International Airport'),
('BRN', 'Switzerland', 'Berne, Bern-Belp'),
('ZDJ', 'Switzerland', 'Berne, Railway Service'),
('BET', 'USA', 'Bethel (AK)'),
('BHO', 'India', 'Bhopal'),
('BBI', 'India', 'Bhubaneswar'),
('BIQ', 'France', 'Biarritz'),
('BIO', 'Spain', 'Bilbao'),
('BIL', 'USA', 'Billings (MT)'),
('BLL', 'Denmark', 'Billund'),
('BTU', 'Malaysia', 'Bintulu'),
('IRO', 'Central African Republic', 'Biraro'),
('BHX', 'United Kingdom', 'Birmingham - Birmingham International Airport'),
('BHM', 'USA', 'Birmingham (AL)'),
('FRU', 'Kyrgyzstan', 'Bishkek - Manas International Airport'),
('BIS', 'USA', 'Bismarck (ND) - Bismarck Municipal Airport'),
('BXO', 'Guinea-Bissau', 'Bissau - Osvaldo Vieiro International Airport'),
('BLK', 'United Kingdom', 'Blackpool'),
('BLT', 'Australia', 'Blackwater'),
('BLZ', 'Malawi', 'Blantyre (Mandala) - Chileka International Airport'),
('BHE', 'New Zealand', 'Blenheim'),
('BFN', 'South Africa', 'Bloemfontein - Bloemfontein Airport'),
('BMI', 'USA', 'Bloomington (IL)'),
('BMG', 'USA', 'Bloomington (IN)'),
('BLF', 'USA', 'Bluefield (WV)'),
('BVB', 'Brazil', 'Boa Vista'),
('BOY', 'Burkina Faso', 'Bobo/Dioulasso'),
('BOO', 'Norway', 'Bodo'),
('BJV', 'Turkey', 'Bodrum - Milas Airport'),
('BOG', 'Colombia', 'Bogota - El Nuevo Dorado International Airport'),
('BOI', 'USA', 'Boise (ID) - Boise Air Terminal'),
('BLQ', 'Italy', 'Bologna'),
('BOM', 'India', 'Bombay (Mumbai) - Chhatrapati Shivaji International'),
('BON', 'Netherlands Antilles', 'Bonaire'),
('YVB', 'Canada', 'Bonaventure, PQ'),
('BOB', 'French Polynesia', 'Bora Bora'),
('BOD', 'France', 'Bordeaux - Bordeaux Airport'),
('BXS', 'USA', 'Borrego Springs (CA)'),
('BOS', 'USA', 'Boston (MA) - General Edward Lawrence Logan'),
('BYK', 'Cote d Ivoire', 'Bouake'),
('BOJ', 'Bulgaria', 'Bourgas/Burgas'),
('BOH', 'United Kingdom', 'Bournemouth'),
('ZBO', 'Australia', 'Bowen'),
('BZN', 'USA', 'Bozeman (MT)'),
('BFD', 'USA', 'Bradford/Warren (PA) /Olean (NY)'),
('BRD', 'USA', 'Brainerd (MN)'),
('BMP', 'Australia', 'Brampton Island'),
('BSB', 'Brazil', 'Brasilia - President Juscelino Kubitschek International'),
('BTS', 'Slovakia', 'Bratislava - M. R. Štefánik Airport'),
('BZV', 'Congo (ROC)', 'Brazzaville - Maya-Maya Airport'),
('BRE', 'Germany', 'Bremen - Bremen Airport (Flughafen Bremen)'),
('VBS', 'Italy', 'Brescia, Montichiari'),
('BES', 'France', 'Brest'),
('BIV', 'Central African Republic', 'Bria'),
('BDR', 'USA', 'Bridgeport (CT)'),
('BGI', 'Barbados', 'Bridgetown - Grantley Adams International'),
('BDS', 'Italy', 'Brindisi'),
('BNE', 'Australia', 'Brisbane'),
('BRS', 'United Kingdom', 'Bristol'),
('BNN', 'Norway', 'Broennoeysund'),
('BHQ', 'Australia', 'Broken Hill'),
('BKX', 'USA', 'Brookings (SD)'),
('BME', 'Australia', 'Broome'),
('BQK', 'USA', 'Brunswick (GA)'),
('BRU', 'Belgium', 'Brussels - Brussels Airport'),
('BGA', 'Colombia', 'Bucaramanga'),
('BUH', 'Romania', 'Bucharest'),
('OTP', 'Romania', 'Bucharest - Henri Coandă International Airport'),
('BUD', 'Hungary', 'Budapest - Budapest Ferihegy International Airport'),
('BUE', 'Argentina', 'Buenos Aires'),
('EZE', 'Argentina', 'Buenos Aires, Ezeiza International Airport'),
('AEP', 'Argentina', 'Buenos Aires, Jorge Newbery'),
('BFO', 'Zimbabwe', 'Buffalo Range'),
('BUF', 'USA', 'Buffalo/Niagara Falls (NY)'),
('BJM', 'Burundi', 'Bujumbura - Bujumbura International Airport'),
('BUQ', 'Zimbabwe', 'Bulawayo'),
('BHC', 'USA', 'Bullhead City (NV)'),
('BDB', 'Australia', 'Bundaberg'),
('BUR', 'USA', 'Burbank (CA)'),
('BRL', 'USA', 'Burlington IA'),
('BTV', 'USA', 'Burlington (VT)'),
('BWT', 'Australia', 'Burnie (Wynyard)'),
('BTM', 'USA', 'Butte (MT)'),
('CAB', 'Angola', 'Cabinda'),
('CAG', 'Italy', 'Cagliari'),
('CNS', 'Australia', 'Cairns'),
('CAI', 'Egypt', 'Cairo - Cairo International Airport'),
('CJC', 'Chile', 'Calama - El Loa'),
('CCU', 'India', 'Calcutta (Kolkata) - Netaji Subhas Chandra'),
('YYC', 'Canada', 'Calgary - Calgary International Airport'),
('CLO', 'Colombia', 'Cali'),
('CCJ', 'India', 'Calicut'),
('CLY', 'France', 'Calvi'),
('YCB', 'Canada', 'Cambridge Bay'),
('CBG', 'United Kingdom', 'Cambrigde'),
('CAL', 'United Kingdom', 'Campbeltown'),
('CGR', 'Brazil', 'Campo Grande'),
('CBR', 'Australia', 'Canberra - Canberra Airport'),
('CUN', 'Mexico', 'Cancun'),
('CEQ', 'France', 'Cannes – Mandelieu Airport'),
('CIW', 'Saint Vincent & the Grenadines', 'Canouan (island) - Canouan Airport'),
('CPT', 'South Africa', 'Cape Town - Cape Town International Airport'),
('CCS', 'Venezuela', 'Caracas - Simón Bolívar International Airport'),
('CWL', 'United Kingdom', 'Cardiff - Cardiff Airport'),
('CLD', 'USA', 'Carlsbad (CA)'),
('CVQ', 'Australia', 'Carnarvon'),
('CRF', 'Central African Republic', 'Carnot'),
('CSN', 'USA', 'Carson City (NV)'),
('CAS', 'Morocco', 'Casablanca'),
('CMN', 'Morocco', 'Casablanca, Mohamed V'),
('LRM', 'Dominican Republic', 'Casa de Campo - La Romana International Airport'),
('CSI', 'Australia', 'Casino'),
('CPR', 'USA', 'Casper (WY)'),
('CST', 'Fiji', 'Castaway'),
('CTG', 'Colombia', 'Cartagena - Rafael Núñez International Airport'),
('SLU', 'Saint Lucia', 'Castries - George F. L. Charles Airport'),
('CTA', 'Italy', 'Catania'),
('CAY', 'French Guiana', 'Cayenne - Cayenne-Rochambeau Airport'),
('CBU', 'Germany', 'Cottbus - Cottbus-Drewitz Airport'),
('CEB', 'Philippines', 'Cebu City - Mactan-Cebu International'),
('CDC', 'USA', 'Cedar City (UT)'),
('CID', 'USA', 'Cedar Rapids IA'),
('CED', 'Australia', 'Ceduna'),
('CES', 'Australia', 'Cessnock'),
('KHV', 'Russia', 'Chabarovsk (Khabarovsk)'),
('CMF', 'France', 'Chambery'),
('CMI', 'USA', 'Champaign (IL)'),
('IXC', 'India', 'Chandigarh - Chandigarh International Airport'),
('CGQ', 'Jilin, PR China', 'Changchun'),
('CHQ', 'Greece', 'Chania'),
('CHG', 'PR China', 'Chaoyang, Beijing - Chaoyang Airport'),
('CHS', 'USA', 'Charleston (SC)'),
('CRW', 'USA', 'Charleston (WV) - Yeager Airport'),
('CLT', 'USA', 'Charlotte (NC)'),
('CHO', 'USA', 'Charlottesville (VA)'),
('CXT', 'Australia', 'Charters Towers'),
('CHA', 'USA', 'Chattanooga (TN)'),
('CTU', 'Sichuan, PR China', 'Chengdu - Shuangliu'),
('MAA', 'India', 'Chennai (Madras)'),
('CYS', 'USA', 'Cheyenne (WY) - Cheyenne Regional Airport'),
('CNX', 'Thailand', 'Chiang Mai - Chiang Mai International Airport'),
('QCB', 'Japan', 'Chiba City'),
('MDW', 'USA', 'Chicago (IL), Midway'),
('ORD', 'USA', 'Chicago (IL), O Hare International Airport'),
('CHI', 'USA', 'Chicago (IL)'),
('CZA', 'Mexico', 'Chichen Itza'),
('CIC', 'USA', 'Chico (CA)'),
('CUU', 'Mexico', 'Chihuahua - Gen Fierro Villalobos'),
('JKH', 'Greece', 'Chios'),
('CIP', 'Zambia', 'Chipata'),
('KIV', 'Moldova', 'Chisinau - Chişinău International Airport'),
('HTA', 'Russia', 'Chita (Tschita)'),
('CTS', 'Japan', 'Sapporo - New Chitose Airport'),
('CJL', 'Pakistan', 'Chitral'),
('CGP', 'Bangladesh', 'Chittagong'),
('CKG', 'Sichuan, PR China', 'Chongqing - Jiangbei International Airport'),
('CHC', 'New Zealand', 'Christchurch'),
('CCZ', 'Bahamas', 'Chub Cay'),
('YYQ', 'Canada', 'Churchill'),
('CFG', 'Cuba', 'Cienfuegos - Jaime González Airport'),
('CVG', 'USA', 'Cincinnati (OH) - Cincinnati/Northern Kentucky Int l'),
('CME', 'Mexico', 'Ciudad Del Carmen'),
('CGU', 'Venezuela', 'Ciudad Guayana'),
('CJS', 'Mexico', 'Ciudad Juarez'),
('CEN', 'Mexico', 'Ciudad Obregon'),
('CVM', 'Mexico', 'Ciudad Victoria'),
('CKB', 'USA', 'Clarksburg (WV)'),
('CMQ', 'Australia', 'Clermont'),
('CFE', 'France', 'Clermont Ferrand'),
('BKL', 'USA', 'Cleveland (OH) , Burke Lakefront'),
('CLE', 'USA', 'Cleveland (OH) - Cleveland Hopkins International'),
('CBB', 'Bolivia', 'Cochabamba'),
('COK', 'India', 'Cochin'),
('COD', 'USA', 'Cody/Powell/Yellowstone (WY)'),
('KCC', 'USA', 'Coffmann Cove (AK)'),
('CFS', 'Australia', 'Coffs Harbour'),
('CJB', 'India', 'Coimbatore'),
('CLQ', 'Mexico', 'Colima'),
('CLL', 'USA', 'College Station/Bryan (TX)'),
('KCE', 'Australia', 'Collinsville'),
('CGN', 'Germany', 'Cologne - Cologne Airport (Flughafen Köln/Bonn)'),
('CMB', 'Sri Lanka', 'Colombo - Bandaranaike International Airport'),
('COS', 'USA', 'Colorado Springs (CO)'),
('CAE', 'USA', 'Columbia (SC) - Columbia Metropolitan Airport'),
('CSG', 'USA', 'Columbus (GA)'),
('CMH', 'USA', 'Columbus (OH) - Port Columbus International'),
('CKY', 'Guinea', 'Conakry - Conakry International Airport'),
('CCR', 'USA', 'Concord (CA) - Buchanan Field'),
('CON', 'USA', 'Concord (NH) - Concord Municipal Airport'),
('CZL', 'Algeria', 'Constantine'),
('CND', 'Romania', 'Constanta (Constanța) - Constanta Int l Airport'),
('CPD', 'Australia', 'Coober Pedy'),
('CTN', 'Australia', 'Cooktown'),
('OOM', 'Australia', 'Cooma'),
('CPH', 'Denmark', 'Copenhagen - Copenhagen Airport'),
('COR', 'Argentina', 'Cordoba'),
('ODB', 'Spain', 'Cordoba'),
('CDV', 'USA', 'Cordova (AK)'),
('CFU', 'Greece', 'Corfu'),
('ORK', 'Ireland', 'Cork'),
('CRP', 'USA', 'Corpus Christi (TX)'),
('COO', 'Benin', 'Cotonou - Cotonou Cadjehoun Airport'),
('CVT', 'United Kingdom', 'Coventry - Baginton'),
('CZM', 'Mexico', 'Cozmel'),
('CGA', 'USA', 'Craig (AK)'),
('CEC', 'USA', 'Crescent City (CA)'),
('CGB', 'Brazil', 'Cuiaba - Marechal Rondon International Airport'),
('CUL', 'Mexico', 'Culiacan'),
('CUR', 'Netherlands Antilles', 'Curacao - Curaçao International Airport'),
('CWB', 'Brazil', 'Curitiba - Afonso Pena International Airport'),
('CYU', 'Philippines', 'Cuyo'),
('DKR', 'Senegal', 'Dakar - Léopold Sédar Senghor International Airport'),
('DLM', 'Turkey', 'Dalaman'),
('DBY', 'Australia', 'Dalby'),
('DLC', 'Liaoning, PR China', 'Dalian - Zhoushuizi International Airport'),
('DAL', 'USA', 'Dallas (TX) , Love Field'),
('DFW', 'USA', 'Dallas/Ft. Worth (TX) - Dallas/Fort Worth International'),
('DJO', 'Cote d Ivoire', 'Daloa'),
('DAM', 'Syria', 'Damascus, International'),
('DMM', 'Saudi Arabien', 'Dammam, King Fahad International'),
('DAN', 'USA', 'Danville (VA)'),
('DAR', 'Tanzania', 'Dar es Salam (Daressalam) - Julius Nyerere Int l'),
('DRW', 'Australia', 'Darwin'),
('DDI', 'Australia', 'Daydream Island'),
('DAY', 'USA', 'Dayton (OH)'),
('DAB', 'USA', 'Daytona Beach (FL)'),
('DEC', 'USA', 'Decatur (IL)'),
('YDF', 'Canada', 'Deer Lake/Corner Brook'),
('DEL', 'India', 'Delhi - Indira Gandhi International Airport'),
('HAG', 'Netherlands', 'Den Haag (The Hague)'),
('DNZ', 'Turkey', 'Denizli'),
('DPS', 'Indonesia', 'Denpasar/Bali'),
('DEN', 'USA', 'Denver (CO) - Denver International Airport'),
('DSK', 'Pakistan', 'Dera Ismail Khan - Dera Ismail Khan Airport'),
('DRB', 'Australia', 'Derby'),
('LDY', 'United Kingdom', 'Derry (Londonderry)'),
('DSM', 'USA', 'Des Moines (IA) - Des Moines International Airport'),
('DET', 'USA', 'Detroit (MI) , Coleman A. Young Municipal'),
('DTW', 'USA', 'Detroit (MI) , Wayne County Airport'),
('DTT', 'USA', 'Detroit (MI) , Metropolitan Area'),
('DVL', 'USA', 'Devils Lake (ND)'),
('DPO', 'Australia', 'Devonport'),
('DHA', 'Saudi Arabia', 'Dhahran'),
('DAC', 'Bangladesh', 'Dhaka - Zia International Airport'),
('DIL', 'Timor Leste (East Timor)', 'Dili - Nicolau Lobato International Airport'),
('DLG', 'USA', 'Dillingham (AK)'),
('DNR', 'France', 'Dinard'),
('DLP', 'France', 'Disneyland Paris'),
('DJE', 'Tunisia', 'Djerba'),
('JIB', 'Djibouti', 'Djibouti (city) - Djibouti-Ambouli International Airport'),
('DOD', 'Tanzania', 'Dodoma - Dodoma Airport'),
('DOH', 'Qatar', 'Doha - Doha International Airport'),
('DSA', 'United Kingdom', 'Doncaster/Sheffield, Robin Hood International Airport'),
('CFN', 'Ireland', 'Donegal (Carrickfin)'),
('DTM', 'Germany', 'Dortmund'),
('DHN', 'USA', 'Dothan (AL)'),
('DLA', 'Cameroon', 'Douala'),
('DRS', 'Germany', 'Dresden - Dresden Airport'),
('DXB', 'United Arab Emirates', 'Dubai - Dubai International Airport'),
('DBO', 'Australia', 'Dubbo'),
('DUB', 'Ireland', 'Dublin - Dublin International Airport'),
('DUJ', 'USA', 'Dubois (PA)'),
('DBV', 'Croatia (Hrvatska)', 'Dubrovnik'),
('DBQ', 'USA', 'Dubuque IA'),
('DUS', 'Germany', 'Duesseldorf - Düsseldorf International Airport'),
('DLH', 'USA', 'Duluth (MN) /Superior (WI)'),
('DND', 'United Kingdom', 'Dundee'),
('DUD', 'New Zealand', 'Dunedin'),
('DKI', 'Australia', 'Dunk Island'),
('DRO', 'USA', 'Durango (CO)'),
('DUR', 'South Africa', 'Durban'),
('DYU', 'Tajikistan', 'Dushanbe (Duschanbe) - Dushanbe Airport'),
('DUT', 'USA', 'Dutch Harbor (AK)'),
('DYA', 'Australia', 'Dysart'),
('DZA', 'Mayotte', 'Dzaoudzi'),
('ELS', 'South Africa', 'East London'),
('IPC', 'Chile', 'Easter Island'),
('EAU', 'USA', 'Eau Clarie (WI)'),
('EDI', 'Scotland, UK', 'Edinburgh - Edinburgh Airport'),
('YEA', 'Canada', 'Edmonton'),
('YEG', 'Canada', 'Edmonton, International'),
('YXD', 'Canada', 'Edmonton, Municipal'),
('EGS', 'Iceland', 'Egilsstadir'),
('EIN', 'Netherlands', 'Eindhoven'),
('AZS', 'Dominican Republic', 'Samana - Samaná El Catey International Airport'),
('EBA', 'Italy', 'Elba Island, Marina Di Campo'),
('ETH', 'Israel', 'Elat'),
('VDA', 'Israel', 'Elat, Ovula'),
('EKI', 'USA', 'Elkhart (IN)'),
('EKO', 'USA', 'Elko (NV)'),
('ELL', 'South Africa', 'Ellisras'),
('EMY', 'Egypt', 'El Minya'),
('ELM', 'USA', 'Elmira (NY)'),
('ELP', 'USA', 'El Paso (TX) - El Paso International Airport'),
('ELY', 'USA', 'Ely (NV)'),
('EDR', 'Australia', 'Emerald'),
('EMD', 'Australia', 'Emerald'),
('ENF', 'Finland', 'Enontekioe'),
('EBB', 'Uganda', 'Entebbe - Entebbe International Airport'),
('ERF', 'Germany', 'Erfurt - Erfurt Airport (Flughafen Erfurt)'),
('ERI', 'USA', 'Erie (PA)'),
('EVN', 'Armenia', 'Eriwan (Yerevan, Jerevan)'),
('ERC', 'Turkey', 'Erzincan'),
('ERZ', 'Turkey', 'Erzurum'),
('EBJ', 'Denmark', 'Esbjerg'),
('ESC', 'USA', 'Escanaba (MI)'),
('EPR', 'Australia', 'Esperance'),
('EUG', 'USA', 'Eugene (OR)'),
('ACV', 'USA', 'Eureka (CA)'),
('EVV', 'USA', 'Evansville (IN)'),
('EVE', 'Norway', 'Evenes'),
('EXT', 'United Kingdom', 'Exeter'),
('FAI', 'USA', 'Fairbanks (AK)'),
('FIE', 'United Kingdom', 'Fair Isle (Shetland)'),
('LYP', 'Pakistan', 'Faisalabad'),
('FAR', 'USA', 'Fargo (ND) (MN)'),
('FMN', 'USA', 'Farmington (NM)'),
('FAO', 'Portugal', 'Faro'),
('FAE', 'Denmark', 'Faroer - Vágar Airport'),
('FYV', 'USA', 'Fayetteville (AR)'),
('FAY', 'USA', 'Fayetteville/Ft. Bragg (NC)'),
('FEZ', 'Morocco', 'Fes'),
('FSC', 'France', 'Figari'),
('FLG', 'USA', 'Flagstaff (AZ)'),
('YFO', 'Canada', 'Flin Flon'),
('FNT', 'USA', 'Flint (MI)'),
('FLR', 'Italy', 'Florence (Firenze) - Peretola Airport'),
('FLO', 'USA', 'Florence (SC)'),
('FLN', 'Brazil', 'Florianopolis'),
('FRO', 'Norway', 'Floro'),
('YFA', 'Canada', 'Fort Albert'),
('FOR', 'Brazil', 'Fortaleza - Pinto Martins Airport'),
('FDF', 'Martinique', 'Fort de France - Martinique Aimé Césaire International'),
('FOD', 'USA', 'Fort Dodge IA'),
('FHU', 'USA', 'Fort Huachuca/Sierra Vista (AZ)'),
('FLL', 'USA', 'Fort Lauderdale/Hollywood (FL)'),
('YMM', 'Canada', 'Fort McMurray'),
('FMY', 'USA', 'Fort Myers, Metropolitan Area (FL)'),
('RSW', 'USA', 'Fort Myers, Southwest Florida Reg (FL)'),
('FRI', 'USA', 'Fort Riley (KS) - Marshall AAF'),
('YSM', 'Canada', 'Fort Smith'),
('FSM', 'USA', 'Fort Smith (AR)'),
('YXJ', 'Canada', 'Fort St. John'),
('VPS', 'USA', 'Fort Walton Beach (FL)'),
('FWA', 'USA', 'Fort Wayne (IN)'),
('DFW', 'USA', 'Fort Worth (TX) - Dallas/Fort Worth International Airport'),
('FOU', 'United Kingdom', 'Foula (Shetland)'),
('FRW', 'Botswana', 'Francistown'),
('FRA', 'Germany', 'Frankfurt/Main - Frankfurt Airport (Rhein-Main-Flughafen)'),
('HHN', 'Germany', 'Frankfurt/Hahn'),
('FKL', 'USA', 'Franklin/Oil City (PA)'),
('YFC', 'Canada', 'Fredericton'),
('FPO', 'Bahamas', 'Freeport - Grand Bahama International Airport'),
('FNA', 'Sierra Leone', 'Freetown - Freetown-Lungi International Airport'),
('FRJ', 'France', 'Frejus'),
('FAT', 'USA', 'Fresno (CA)'),
('FDH', 'Germany', 'Friedrichshafen - Bodensee-Airport Friedrichshafen'),
('FUE', 'Spain', 'Fuerteventura'),
('FJR', 'United Arab Emirates', 'Fujairah, International Airport'),
('FUK', 'Japan', 'Fukuoka'),
('FKS', 'Japan', 'Fukushima - Fukushima Airport'),
('FNC', 'Portugal', 'Funchal'),
('FUT', 'Wallis and Futuna Islands', 'Futuna'),
('GBE', 'Botswana', 'Gaborone - Sir Seretse Khama International Airport'),
('GAD', 'USA', 'Gadsden (AL)'),
('GNV', 'USA', 'Gainesville (FL)'),
('GWY', 'Ireland', 'Galway'),
('YQX', 'Canada', 'Gander'),
('GOU', 'Cameroon', 'Garoua'),
('GZA', 'Palestinian Territory', 'Gaza City - Gaza International Airport'),
('GZT', 'Turkey', 'Gaziantep'),
('GDN', 'Poland', 'Gdansk'),
('GEX', 'Australia', 'Geelong'),
('GVA', 'Switzerland', 'Geneva - Geneva-Cointrin International Airport'),
('GOA', 'Italy', 'Genoa'),
('GRJ', 'South Africa', 'George'),
('GEO', 'Guyana', 'Georgetown - Cheddi Jagan International Airport'),
('GET', 'Australia', 'Geraldton'),
('GRO', 'Spain', 'Gerona'),
('GNE', 'Belgium', 'Ghent (Gent)'),
('GIB', 'Gibraltar', 'Gibraltar'),
('GCC', 'USA', 'Gilette (WY)'),
('GIL', 'Pakistan', 'Gilgit'),
('YGX', 'Canada', 'Gillam'),
('GLT', 'Australia', 'Gladstone'),
('PIK', 'United Kingdom', 'Glasgow, Prestwick'),
('GLA', 'United Kingdom', 'Glasgow'),
('GGW', 'USA', 'Glasgow (MT)'),
('GDV', 'USA', 'Glendive (MT)'),
('GOI', 'India', 'Goa'),
('GYN', 'Brazil', 'Goiania, Santa Genoveva Airport'),
('OOL', 'Australia', 'Gold Coast'),
('GOO', 'Australia', 'Goondiwindi'),
('YYR', 'Canada', 'Goose Bay'),
('GOZ', 'Bulgaria', 'Gorna'),
('GOT', 'Sweden', 'Gothenburg (Göteborg) - Landvetter'),
('GOV', 'Australia', 'Gove (Nhulunbuy)'),
('GHB', 'Bahamas', 'Govenors Harbour'),
('GRX', 'Spain', 'Granada'),
('FPO', 'Bahamas', 'Grand Bahama International'),
('GCN', 'USA', 'Grand Canyon (AZ)'),
('GCM', 'Cayman Islands', 'Grand Cayman - Owen Roberts International'),
('GFK', 'USA', 'Grand Forks (ND)'),
('GJT', 'USA', 'Grand Junction (CO)'),
('GRR', 'USA', 'Grand Rapids (MI)'),
('GPZ', 'USA', 'Grand Rapids (MN)'),
('GRZ', 'Austria', 'Graz'),
('GTF', 'USA', 'Great Falls (MT)'),
('GKL', 'Australia', 'Great Keppel Island'),
('GRB', 'USA', 'Green Bay (WI)'),
('LWB', 'USA', 'Greenbrier/Lewisburg (WV)'),
('GSO', 'USA', 'Greensboro/Winston Salem (NC)'),
('GLH', 'USA', 'Greenville (MS)'),
('PGV', 'USA', 'Greenville (NC)'),
('GSP', 'USA', 'Greenville/Spartanburg (SC)'),
('GND', 'Grenada', 'Grenada - Point Salines Airport also Maurice Bishop'),
('GNB', 'France', 'Grenoble'),
('GFF', 'Australia', 'Griffith'),
('GRQ', 'Netherlands', 'Groningen - Eelde'),
('GTE', 'Australia', 'Groote Eylandt - Alyangula'),
('GON', 'USA', 'Groton/New London (CT)'),
('GDL', 'Mexico', 'Guadalajara'),
('GSI', 'Solomon Islands', 'Guadalcanal'),
('GUM', 'Guam', 'Guam'),
('CAN', 'Guangdong, PR China', 'Guangzhou (Canton) - Baiyun International Airport'),
('GRU', 'Brazil', 'Sao Paulo - Guarulhos International'),
('GUA', 'Guatemala', 'Guatemala City - La Aurora International Airport'),
('GYE', 'Ecuador', 'Guayaquil - Simon Bolivar'),
('GCI', 'Channel Islands', 'Guernsey'),
('GTI', 'Germany', 'Guettin'),
('GPT', 'USA', 'Gulfport/Biloxi (MS)'),
('KWL', 'Guangxi, PR China', 'Guilin - Liangjiang'),
('ULU', 'Uganda', 'Gulu'),
('GUC', 'USA', 'Gunnison/Crested Butte (CO)'),
('GAU', 'India', 'Guwahati'),
('GWD', 'Pakistan', 'Gwadar'),
('GWE', 'Zimbabwe', 'Gweru'),
('GYP', 'Australia', 'Gympie'),
('HAC', 'Japan', 'Hachijo Jima'),
('GUM', 'Guam', 'Hagåtña - Guam International Airport'),
('HFA', 'Israel', 'Haifa'),
('HNS', 'USA', 'Haines (AK)'),
('HKD', 'Japan', 'Hakodate'),
('YHZ', 'Canada', 'Halifax International'),
('YUX', 'Canada', 'Hall Beach'),
('HAM', 'Germany', 'Hamburg - Fuhlsbuettel'),
('HLT', 'Australia', 'Hamilton'),
('YHM', 'Canada', 'Hamilton'),
('HLZ', 'New Zealand', 'Hamilton'),
('HTI', 'Australia', 'Hamilton Island'),
('HFT', 'Norway', 'Hammerfest'),
('CMX', 'USA', 'Hancock (MI)'),
('HGH', 'Zhejiang, PR China', 'Hangchow (Hangzhou)'),
('HAJ', 'Germany', 'Hannover'),
('HAN', 'Vietnam', 'Hanoi - Noi Bai International Airport'),
('HRE', 'Zimbabwe', 'Harare - Harare International Airport'),
('HRB', 'Heilongjiang, PR China', 'Harbin (Haerbin)'),
('HRL', 'USA', 'Harlingen/South Padre Island (TX)'),
('YHR', 'Canada', 'Harrington Harbour, PQ'),
('HAR', 'USA', 'Harrisburg (PA) - Harrisburg Skyport'),
('MDT', 'USA', 'Harrisburg (PA) - Harrisburg International'),
('BDL', 'USA', 'Hartford (CT) /Springfield (MA)'),
('HDY', 'Thailand', 'Hatyai (Hat Yai)'),
('HAU', 'Norway', 'Haugesund'),
('HAV', 'Cuba', 'Havana - José Martí International'),
('HVR', 'USA', 'Havre (MT)'),
('HIS', 'Australia', 'Hayman Island'),
('HLN', 'USA', 'Helena (MT)'),
('JHE', 'Sweden', 'Helsingborg'),
('HEL', 'Finland', 'Helsinki - Vantaa'),
('HER', 'Greece', 'Heraklion'),
('HMO', 'Mexico', 'Hermosillo - Gen. Pesqueira Garcia'),
('HVB', 'Australia', 'Hervey Bay'),
('HIB', 'USA', 'Hibbing (MN)'),
('HKY', 'USA', 'Hickory (NC)'),
('ITO', 'USA', 'Hilo (HI)'),
('HHH', 'USA', 'Hilton Head Island (SC)'),
('HNK', 'Australia', 'Hinchinbrook Island'),
('HIJ', 'Japan', 'Hiroshima International'),
('SGN', 'Viet Nam', 'Ho Chi Minh City (Saigon) - Tan Son Nhat International'),
('HBA', 'Australia', 'Hobart'),
('HOQ', 'Germany', 'Hof'),
('HOG', 'Cuba', 'Holguin'),
('HMH', 'Australia', 'Home Hill'),
('HOM', 'USA', 'Homer (AK)'),
('HKG', 'Hong Kong', 'Hong Kong - International Airport (HKIA)'),
('ZJK', 'Hong Kong', 'Hong Kong - Chek Lap Kok'),
('HIR', 'Solomon Islands', 'Honiara Henderson International'),
('HNL', 'USA', 'Honolulu (HI) - Honolulu International Airport'),
('HNH', 'USA', 'Hoonah (AK)'),
('HOR', 'Portugal', 'Horta'),
('HOU', 'USA', 'Houston (TX) , Hobby'),
('IAH', 'USA', 'Houston, TX - George Bush Intercontinental Airport'),
('HUH', 'French Polynesia', 'Huahine'),
('HUX', 'Mexico', 'Huatulco'),
('HUI', 'Viet Nam', 'Hue - Phu Bai'),
('HUY', 'United Kingdom', 'Humberside'),
('HTS', 'USA', 'Huntington (WV)'),
('HSV', 'USA', 'Huntsville (AL)'),
('HRG', 'Egypt', 'Hurghada International'),
('HON', 'USA', 'Huron (SD)'),
('HWN', 'Zimbabwe', 'Hwange National Park'),
('HYA', 'USA', 'Hyannis (MA)'),
('HYG', 'USA', 'Hydaburg (AK)'),
('HYD', 'India', 'Hyderabad - Rajiv Gandhi International Airport'),
('HDD', 'Pakistan', 'Hyderabad'),
('IBZ', 'Ibiza/Spain', 'Ibiza'),
('IDA', 'USA', 'Idaho Falls (ID)'),
('IGR', 'Argentina', 'Iguazu, Cataratas'),
('ILP', 'New Caledonia', 'Ile des Pins'),
('IOU', 'New Caledonia', 'Ile Ouen'),
('ILI', 'USA', 'Iliamna (AK)'),
('IPL', 'USA', 'Imperial (CA)'),
('IVC', 'New Zealand', 'Incercargill'),
('ICN', 'Korea South', 'Incheon, Incheon International Airport'),
('IND', 'USA', 'Indianapolis (IN) International'),
('IGH', 'Australia', 'Ingham'),
('IFL', 'Australia', 'Innisfail'),
('INN', 'Austria', 'Innsbruck - Kranebitten'),
('INL', 'USA', 'International Falls (MN)'),
('YEV', 'Canada', 'Inuvik'),
('IVC', 'New Zealand', 'Invercargill'),
('INV', 'United Kingdom', 'Inverness'),
('IYK', 'USA', 'Inykern (CA)'),
('YFB', 'Canada', 'Iqaluit (Frobisher Bay)'),
('IQT', 'Peru', 'Iquitos'),
('IKT', 'Russia', 'Irkutsk'),
('ISG', 'Japan', 'Ishigaki - New Ishigaki Airport'),
('ISB', 'Pakistan', 'Islamabad - Benazir Bhutto International Airport'),
('ILY', 'United Kingdom', 'Islay'),
('IOM', ' ', 'Isle of Man'),
('IST', 'Turkey', 'Istanbul - Istanbul Atatürk Airport'),
('SAW', 'Turkey', 'Istanbul - Sabiha Gokcen'),
('ITH', 'USA', 'Ithaca/Cortland (NY)'),
('IVL', 'Finland', 'Ivalo'),
('ZIH', 'Mexico', 'Ixtapa/Zihuatenejo'),
('IZM', 'Turkey', 'Izmir'),
('ADB', 'Turkey', 'Izmir - Adnan Menderes Airport'),
('JAC', 'USA', 'Jackson Hole (WY)'),
('JXN', 'USA', 'Jackson (MI) - Reynolds Municipal'),
('MJQ', 'USA', 'Jackson,  MN  '),
('JAN', 'USA', 'Jackson (MS) - Jackson Internationall'),
('HKS', 'USA', 'Jackson (MS) - Hawkins Field   '),
('MKL', 'USA', 'Jackson (TN) - Mckellar'),
('JAC', 'USA', 'Jackson Hole (WY)'),
('LRF', 'USA', 'Jacksonville (AR)  Little Rock AFB   '),
('NZC', 'USA', 'Jacksonville (FL) - Cecil Field NAS   '),
('NIP', 'USA', 'Jacksonville (FL) Jacksonville NAS   '),
('JAX', 'USA', 'Jacksonville (FL) - International'),
('CRG', 'USA', 'Jacksonville (FL) - Craig Municipal   '),
('IJX', 'USA', 'Jacksonville (IL) - Municipal Airport'),
('OAJ', 'USA', 'Jacksonville (NC)'),
('JKV', 'USA', 'Jacksonville (TX)'),
('JAK', 'Haiti', 'Jacmel   '),
('JAG', 'Pakistan', 'Jacobabad'),
('JCM', 'Brazil', 'Jacobina   '),
('JAQ', 'Papua New Guinea', 'Jacquinot Bay'),
('JAF', 'Sri Lanka', 'Jaffna - Kankesanturai'),
('JGB', 'India', 'Jagdalpur'),
('JAI', 'India', 'Jaipur - Sanganeer'),
('JSA', 'India', 'Jaisalmer   '),
('HLP', 'Indonesia', 'Jakarta - Halim Perdana Kusuma'),
('JKT', 'Indonesia', 'Jakarta - Metropolitan Area'),
('CGK', 'Indonesia', 'Jakarta - Soekarno-Hatta International'),
('JAA', 'Afghanistan', 'Jalalabad    '),
('JLR', 'India', 'Jalandhar'),
('JAL', 'Mexico', 'Jalapa'),
('JLS', 'Brazil', 'Jales'),
('UIT', 'Marshall Islands', 'Jaluit Island  '),
('JMB', 'Angola', 'Jamba'),
('DJB', 'Indonesia ', 'Jambi - Sultan Taha Syarifudn'),
('JAM', 'Bulgaria', 'Jambol'),
('JMS', 'USA', 'Jamestown (ND)'),
('JHW', 'USA', 'Jamestown (NY)'),
('IXJ', 'India', 'Jammu - Satwari'),
('JGA', 'India', 'Jamnagar - Govardhanpur'),
('IXW', 'India', 'Jamshedpur - Sonari Airport'),
('JKR', 'Nepal', 'Janakpur'),
('JAD', 'Australia', 'Jandakot'),
('JVL', 'USA', 'Janesville (WI) - Rock County'),
('JNA', 'Brazil', 'Januaria'),
('JQE', 'Panama', 'Jaque   '),
('JTI', 'Brazil', 'Jatai'),
('JAU', 'Peru', 'Jauja'),
('DJJ', 'Indonesia', 'Jayapura - Sentani'),
('JED', 'Saudi Arabia', 'Jeddah - King Abdulaziz International'),
('JEF', 'USA', 'Jefferson City (MO) - Jefferson Memorial'),
('JEE', 'Haiti', 'Jeremie - Jeremie Airport'),
('XRY', 'Spain', 'Jerez de la Frontera/Cadiz - La Parra'),
('JER', 'Channel Islands', 'Jersey'),
('JRS', 'Israel', 'Jerusalem - Atarot Airport (closed)'),
('JSR', 'Bangladesh', 'Jessore - Jessore Airport'),
('PYB', 'India', 'Jeypore - Jeypore Airport'),
('JGS', 'Jiangxi, China', 'Ji an'),
('JMU', 'PR China', 'Jiamusi - Jiamusi Airport'),
('JGN', 'PR China', 'Jiayuguan - Jiayuguan Airport'),
('GJL', 'Algeria', 'Jijel'),
('JIJ', 'Ethiopia', 'Jijiga'),
('JIL', 'PR China', 'Jilin'),
('JIM', 'Ethiopia', 'Jimma'),
('TNA', 'Shandong, PR China', 'Jinan'),
('JDZ', 'PR China', 'Jingdezhen'),
('JHG', 'PR China', 'Jinghong - Gasa Airport'),
('JNG', 'PR China', 'Jining'),
('JIN', 'Uganda', 'Jinja'),
('JJN', 'PR China', 'Jinjiang'),
('BCO', 'Ethiopia', 'Jinka - Baco/Jinka Airport'),
('JNZ', 'PR China', 'Jinzhou - Jinzhou Airport'),
('JIP', 'Ecuador', 'Jipijapa'),
('JIR', 'Nepal', 'Jiri'),
('JIU', 'PR China', 'Jiujiang - Jiujiang Lushan Airport'),
('JIW', 'Pakistan', 'Jiwani'),
('JCB', 'Brazil', 'Joacaba'),
('JPA', 'Brazil', 'Joao Pessoa - Castro Pinto Airport'),
('JDH', 'India', 'Jodhpur'),
('JKG', 'Sweden', 'Jönköping (Jonkoping) - Axamo Airport'),
('JOE', 'Finland', 'Joensuu'),
('JNB', 'South Africa', 'Johannesburg - OR Tambo International Airport'),
('BGM', 'USA', 'Johnson City (NY) - Binghamton/Endicott/Johnson'),
('JON', 'USA', 'Johnston Island'),
('JST', 'USA', 'Johnstown (PA)'),
('JHB', 'Malaysia', 'Johor Bahru - Sultan Ismail International'),
('JOI', 'Brazil', 'Joinville - Cubatao Airport'),
('JOL', 'Philippines', 'Jolo'),
('JMO', 'Nepal', 'Jomsom'),
('JBR', 'USA', 'Jonesboro (AR)  Jonesboro Airport'),
('JLN', 'USA', 'Joplin (MO)'),
('JRH', 'India', 'Jorhat - Rowriah Airport'),
('JOS', 'Nigeria', 'Jos'),
('JSM', 'Argentina', 'Jose De San Martin'),
('AJF', 'Saudi Arabia', 'Jouf'),
('JJI', 'Peru', 'Juanjui'),
('JUB', 'South Sudan', 'Juba'),
('JUI', 'Germany', 'Juist (island)'),
('JDF', 'Brazil', 'Juiz De Fora - Francisco De Assis Airport'),
('JUJ', 'Argentina', 'Jujuy - El Cadillal Airport'),
('JCK', 'Australia', 'Julia Creek'),
('JUL', 'Peru', 'Juliaca'),
('JUM', 'Nepal', 'Jumla'),
('JUN', 'Australia', 'Jundah'),
('JNU', 'USA', 'Juneau (AK) - Juneau International Airport'),
('JNI', 'Argentina', 'Junin'),
('JUT', 'Honduras', 'Juticalpa'),
('JWA', 'Botswana', 'Jwaneng'),
('JYV', 'Finland', 'Jyväskylä (Jyvaskyla)'),
('KBL', 'Afghanistan', 'Kabul - Khwaja Rawash Airport'),
('KOJ', 'Japan', 'Kagoshima'),
('KCM', 'Turkey', 'Kahramanmaras'),
('OGG', 'USA', 'Kahului (HI)'),
('KAJ', 'Finland', 'Kajaani'),
('KLX', 'Greece', 'Kalamata'),
('AZO', 'USA', 'Kalamazoo/Battle Creek (MI)'),
('KGI', 'Australia', 'Kalgoorlie'),
('KGD', 'Russia', 'Kaliningrad'),
('FCA', 'USA', 'Kalispell (MT)'),
('KLR', 'Sweden', 'Kalmar'),
('YKA', 'Canada', 'Kamloops, BC'),
('MUE', 'USA', 'Kamuela (HI)'),
('KAN', 'Nigeria', 'Kano'),
('KNU', 'India', 'Kanpur'),
('MCI', 'USA', 'Kansas City (MO) - Kansas City International Airport'),
('KHH', 'Taiwan', 'Kaohsiung International'),
('JHM', 'USA', 'Kapalua West (HI)'),
('KHI', 'Pakistan', 'Karachi - Jinnah International Airport'),
('FKB', 'Germany', 'Karlsruhe-Baden - Soellingen'),
('KSD', 'Sweden', 'Karlstad'),
('AOK', 'Greece', 'Karpathos'),
('KTA', 'Australia', 'Karratha'),
('KYS', 'Turkey', 'Kars'),
('KRB', 'Australia', 'Karumba'),
('KRP', 'Denmark', 'Karup'),
('ZKE', 'Canada', 'Kaschechawan, PQ'),
('KSL', 'Sudan', 'Kassala'),
('KTR', 'Australia', 'Katherine'),
('KTM', 'Nepal', 'Kathmandu - Tribhuvan International Airport'),
('MPA', 'Namibia', 'Katima Mulilo/Mpacha'),
('KHJ', 'Finland', 'Kauhajoki'),
('MKK', 'USA', 'Kaunakakai (HI)'),
('KVA', 'Greece', 'Kavalla'),
('ASR', 'Turkey', 'Kayseri'),
('KZN', 'Russia', 'Kazan - Kazan International Airport'),
('KMP', 'Namibia', 'Keetmanshoop'),
('YLW', 'Canada', 'Kelowna, BC'),
('KEM', 'Finland', 'Kemi/Tornio'),
('ENA', 'USA', 'Kenai (AK)'),
('MSE', 'United Kingdom', 'Kent (Manston) Kent International'),
('KIR', 'Ireland', 'Kerry County'),
('KTN', 'USA', 'Ketchikan (AK)'),
('EYW', 'USA', 'Key West (FL)'),
('AHB', 'Saudi Arabia', 'Khamis Mushayat'),
('UVL', 'Egypt', 'Kharga - New Valley'),
('HRK', 'Ukraine', 'Kharkov'),
('KRT', 'Sudan', 'Khartoum - Khartoum International Airport'),
('KDD', 'Pakistan', 'Khuzdar'),
('KEL', 'Germany', 'Kiel - Holtenau'),
('KBP', 'Ukraine', 'Kiev - Borispol'),
('IEV', 'Ukraine', 'Kiev - Zhulhany'),
('KGL', 'Rwanda', 'Kigali - Gregoire Kayibanda'),
('JRO', 'Tanzania', 'Kilimadjaro'),
('ILE', 'USA', 'Killeem (TX)'),
('KIM', 'South Africa', 'Kimberley'),
('KNS', 'King Island (Australia)', 'King Island'),
('AKN', 'USA', 'King Salomon (AK)'),
('KGC', 'Australia', 'Kingscote'),
('KIN', 'Jamaica', 'Kingston - Norman Manley'),
('ISO', 'USA', 'Kingston (NC)'),
('SVD', 'Saint Vincent and the Grenadines', 'Kingstown - E. T. Joshua Airport'),
('FIH', 'Congo (DRC)', 'Kinshasa - N Djili'),
('CXI', 'Kiribati', 'Kiritimati (island) - Cassidy International Airport'),
('KKN', 'Norway', 'Kirkenes'),
('KIK', 'Iraq', 'Kirkuk'),
('KOI', 'United Kingdom', 'Kirkwall (Orkney)'),
('KRN', 'Sweden', 'Kiruna'),
('FKI', 'Congo (DRC)', 'Kisangani'),
('KTT', 'Finland', 'Kittilä'),
('KIW', 'Zambia', 'Kitwe'),
('KLU', 'Austria', 'Klagenfurt'),
('LMT', 'USA', 'Klamath Fall (OR)'),
('KLW', 'USA', 'Klawock (AK)'),
('KLZ', 'South Africa', 'Kleinsee'),
('NOC', 'Ireland', 'Knock'),
('TYS', 'USA', 'Knoxville (TN)'),
('UKB', 'Japan', 'Kobe'),
('KCZ', 'Japan', 'Kochi'),
('CGN', 'Germany', 'Köln, Köln/Bonn'),
('ADQ', 'USA', 'Kodiak (AK)'),
('OHT', 'Pakistan', 'Kohat'),
('KOK', 'Finland', 'Kokkola/Pietarsaari'),
('CCU', 'India', 'Kolkata (Calcutta) - Netaji Subhas Chandra'),
('KMQ', 'Japan', 'Komatsu'),
('KOA', 'USA', 'Kona (HI)'),
('KYA', 'Turkey', 'Konya'),
('HGO', 'Cote d Ivoire', 'Korhogo'),
('KGS', 'Greece', 'Kos'),
('BKI', 'Malaysia', 'Kota Kinabalu'),
('OTZ', 'USA', 'Kotzbue (AK)'),
('KWM', 'Australia', 'Kowanyama'),
('KRK', 'Poland', 'Krakow (Cracow) - John Paul II International Airport'),
('KRS', 'Norway', 'Kristiansand'),
('KID', 'Sweden', 'Kristianstad'),
('KSU', 'Norway', 'Kristiansund'),
('KUL', 'Malaysia', 'Kuala Lumpur - International Airport'),
('SZB', 'Malaysia', 'Kuala Lumpur - Sultan Abdul Aziz Shah'),
('KUA', 'Malaysia', 'Kuantan'),
('KCH', 'Malaysia', 'Kuching'),
('KMJ', 'Japan', 'Kumamoto'),
('KNX', 'Australia', 'Kununurra'),
('KUO', 'Finland', 'Kuopio'),
('KUH', 'Japan', 'Kushiro'),
('YVP', 'Canada', 'Kuujjuaq (FortChimo)'),
('YGW', 'Canada', 'Kuujjuarapik'),
('KAO', 'Finland', 'Kuusamo'),
('KWI', 'Kuwait', 'Kuwait - Kuwait International'),
('UKY', 'Japan', 'Kyoto'),
('LEK', 'Guinea', 'Labe'),
('WLB', 'USA', 'Labouchere Bay (AK)'),
('LBU', 'Malaysia', 'Labuan'),
('XLB', 'Canada', 'Lac Brochet, MB'),
('LCG', 'Spain', 'La Coruna'),
('LSE', 'USA', 'La Crosse (WI)'),
('LAE', 'Papua New Guinea', 'Lae - Lae Nadzab Airport'),
('LRH', 'France', 'La Rochelle'),
('LAF', 'USA', 'Lafayette (IN)'),
('LFT', 'USA', 'Lafayette, La'),
('LOS', 'Nigeria', 'Lagos - Murtala Muhammed Airport'),
('YGL', 'Canada', 'La Grande'),
('LHE', 'Pakistan', 'Lahore'),
('LCH', 'USA', 'Lake Charles (LA)'),
('HII', 'USA', 'Lake Havasu City (AZ)'),
('TVL', 'USA', 'Lake Tahoe (CA)'),
('LKL', 'Norway', 'Lakselv'),
('LBQ', 'Gabon', 'Lambarene'),
('SUF', 'Italy', 'Lamezia Terme'),
('LMP', 'Italy', 'Lampedusa'),
('LNY', 'USA', 'Lanai City (HI)'),
('LNS', 'USA', 'Lancaster (PA)'),
('LEQ', 'United Kingdom', 'Lands End'),
('LGK', 'Malaysia', 'Langkawi (islands)'),
('LAI', 'France', 'Lannion'),
('HLA', 'South Africa', 'Lanseria'),
('LAN', 'USA', 'Lansing (MI)'),
('LPB', 'Bolivia', 'La Paz - El Alto'),
('LAP', 'Mexico', 'La Paz - Leon'),
('LPP', 'Finland', 'Lappeenranta'),
('LAR', 'USA', 'Laramie (WY)'),
('LRD', 'USA', 'Laredo (TX)'),
('LCA', 'Cyprus', 'Larnaca'),
('LPA', 'Spain', 'Las Palmas'),
('LAS', 'USA', 'Las Vegas (NV)'),
('LBE', 'USA', 'Latrobe (PA)'),
('LST', 'Australia', 'Launceston'),
('PIB', 'USA', 'Laurel/Hattisburg (MS)'),
('LVO', 'Australia', 'Laverton'),
('LAW', 'USA', 'Lawton (OK)'),
('LZC', 'Mexico', 'Lazaro Cardenas'),
('YLR', 'Canada', 'Leaf Rapids'),
('LEA', 'Australia', 'Learmouth (Exmouth)'),
('LEB', 'USA', 'Lebanon (NH)'),
('LBA', 'United Kingdom', 'Leeds/Bradford'),
('LER', 'Australia', 'Leinster'),
('LEJ', 'Germany', 'Leipzig'),
('LEY', 'Netherlands', 'Lelystad'),
('BJX', 'Mexico', 'Leon'),
('LNO', 'Australia', 'Leonora'),
('LWK', 'United Kingdom', 'Lerwick/Tingwall (Shetland Islands)'),
('LWS', 'USA', 'Lewiston (ID)'),
('LWT', 'USA', 'Lewistown (MT)'),
('LEX', 'USA', 'Lexington (KY)'),
('LBV', 'Gabon', 'Libreville'),
('LDK', 'Sweden', 'Lidkoeping'),
('LGG', 'Belgium', 'Liege'),
('LIF', 'Loyaute, Pazifik', 'Lifou'),
('LIH', 'USA', 'Lihue (HI)'),
('LIL', 'France', 'Lille - Lille Airport'),
('LLW', 'Malawi', 'Lilongwe - Lilongwe International'),
('LIM', 'Peru', 'Lima - J Chavez International'),
('QLI', 'Cyprus', 'Limassol'),
('LIG', 'France', 'Limoges'),
('LNK', 'USA', 'Lincoln (NE)'),
('LDC', 'Australia', 'Lindeman Island'),
('LNZ', 'Austria', 'Linz - Hoersching'),
('LIQ', 'Congo (DRC)', 'Lisala'),
('LIS', 'Portugal', 'Lisbon - Lisboa'),
('LSY', 'Australia', 'Lismore'),
('LIT', 'USA', 'Little Rock (AR)'),
('LPL', 'United Kingdom', 'Liverpool'),
('LZR', 'Australia', 'Lizard Island'),
('LJU', 'Slovenia', 'Ljubljana - Brnik'),
('IRG', 'Australia', 'Lockhart River'),
('LFW', 'Togo', 'Lome'),
('YXU', 'Canada', 'London'),
('LON', 'United Kingdom', 'London Metropolitan Area'),
('LCY', 'United Kingdom', 'London - City Airport'),
('LGW', 'United Kingdom', 'London - Gatwick'),
('LHR', 'United Kingdom', 'London - Heathrow'),
('LTN', 'United Kingdom', 'London - Luton'),
('STN', 'United Kingdom', 'London - Stansted'),
('LDY', 'United Kingdom', 'Londonderry - Eglinton'),
('LGB', 'USA', 'Long Beach (CA)'),
('LIJ', 'USA', 'Long Island (AK)'),
('ISP', 'USA', 'Long Island, Islip (NY) - Mac Arthur'),
('LRE', 'Australia', 'Longreach'),
('GGG', 'USA', 'Longview/Kilgore (TX)'),
('LYR', 'Svalbard/Norway', 'Longyearbyen - Svalbard'),
('LTO', 'Mexico', 'Loreto'),
('LRT', 'France', 'Lorient'),
('LAX', 'USA', 'Los Angeles (CA) - International'),
('SJD', 'Mexico', 'Los Cabos'),
('LMM', 'Mexico', 'Los Mochis'),
('TFN', 'Teneriffa/Spain', 'Los Rodeos'),
('LSZ', 'Croatia (Hrvatska)', 'Losinj - Losinj Arpt'),
('LDE', 'France', 'Lourdes/Tarbes'),
('SDF', 'USA', 'Louisville (KY)'),
('LAD', 'Angola', 'Luanda - 4 de Fevereiro'),
('LBB', 'USA', 'Lubbock (TX)'),
('LKO', 'India', 'Lucknow'),
('LUD', 'Namibia', 'Luederitz'),
('MLA', 'Malta', 'Luga'),
('LUG', 'Switzerland', 'Lugano'),
('LLA', 'Sweden', 'Lulea'),
('FBM', 'Congo (DRC)', 'Lumbumbashi'),
('LUN', 'Zambia', 'Lusaka - Lusaka International Airport'),
('LUJ', 'South Africa', 'Lusisiki'),
('LUX', 'Luxembourg', 'Luxembourg'),
('LUM', 'Yunnan, PR China', 'Luxi - Mangshi'),
('LXR', 'Egypt', 'Luxor'),
('LWO', 'Ukraine', 'Lvov (Lwow, Lemberg)'),
('LYX', 'United Kingdom', 'Lydd - Lydd International Airport'),
('LYH', 'USA', 'Lynchburg (VA)'),
('LYS', 'France', 'Lyon - Lyon-Saint Exupéry Airport official website'),
('LYO', 'USA', 'Lyons (KS) - Rice County Municipal'),
('MST', 'Netherlands', 'Maastricht/Aachen'),
('MCP', 'Brazil', 'Macapa - Alberto Alcolumbre International Airport'),
('MFM', 'Macau, China SAR', 'Macau - Macau International Airport'),
('MCZ', 'Brazil', 'Maceio - Zumbi dos Palmares International Airport'),
('MKY', 'Australia', 'Mackay'),
('MCN', 'USA', 'Macon (GA)'),
('NOP', 'Philippines', 'Mactan Island - Nab'),
('MED', 'Saudi Arabia', 'Madinah (Medina) - Mohammad Bin Abdulaziz'),
('MSN', 'USA', 'Madison (WI) - Dane County Regional Airport'),
('MAA', 'India', 'Madras (Chennai) - Chennai International Airport'),
('MAD', 'Spain', 'Madrid - Barajas Airport'),
('SEZ', 'Seychelles', 'Mahe - Seychelles International'),
('MAH', 'Spain', 'Mahon'),
('MTL', 'Australia', 'Maitland'),
('MJN', 'Madagascar', 'Majunga'),
('MZG', 'Taiwan', 'Makung'),
('SSG', 'Equatorial Guinea', 'Malabo - Malabo International Airport'),
('AGP', 'Spain', 'Malaga'),
('MLX', 'Turkey', 'Malatya'),
('MLE', 'Maledives', 'Male - Velana International Airport'),
('MYD', 'Kenya', 'Malindi'),
('MMA', 'Sweden', 'Malmo (Malmoe)'),
('MMX', 'Sweden', 'Malmo (Malmö) - Malmö Airport'),
('MJC', 'Cote d Ivoire', 'Man'),
('MGA', 'Nicaragua', 'Managua - Augusto C Sandino'),
('MAO', 'Brazil', 'Manaus - Eduardo Gomes International Airport'),
('MAN', 'United Kingdom', 'Manchester'),
('MHT', 'USA', 'Manchester (NH)'),
('MDL', 'Myanmar', 'Mandalay - Mandalay-Annisaton Airport'),
('MFO', 'Papua New Guinea', 'Manguna'),
('XMH', 'French Polynesia', 'Manihi'),
('MNL', 'Philippines', 'Manila - Ninoy Aquino International'),
('ZLO', 'Mexico', 'Manzanillo'),
('MTS', 'Swaziland', 'Manzini - Matsapha International'),
('MPM', 'Mozambique', 'Maputo - Maputo International'),
('MDQ', 'Argentina', 'Mar del Plata'),
('MAR', 'Venezuela', 'Maracaibo - La Chinita International'),
('MFQ', 'Niger', 'Maradi'),
('KCM', 'Turkey', 'Maras'),
('MTH', 'USA', 'Marathon (FL)'),
('MQM', 'Turkey', 'Mardin'),
('MEE', 'New Caledonia', 'Mare'),
('MGH', 'South Africa', 'Margate'),
('PMV', 'Venezuela', 'Margerita'),
('MBX', 'Slovenia', 'Maribor'),
('MHQ', 'Finland', 'Mariehamn (Maarianhamina)'),
('MVR', 'Cameroon', 'Maroua'),
('MQT', 'USA', 'Marquette (MI)'),
('RAK', 'Morocco', 'Marrakesh - Menara Airport'),
('RMF', 'Egypt', 'Marsa Alam'),
('MUH', 'Egypt', 'Marsa Matrah (Marsa Matruh)'),
('MRS', 'France', 'Marseille - Marseille Provence Airport'),
('MHH', 'Bahamas', 'Marsh Harbour'),
('MVY', 'USA', 'Marthas Vineyard (MA)'),
('MRB', 'USA', 'Martinsburg (WV)'),
('MBH', 'Australia', 'Maryborough'),
('MSU', 'Lesotho', 'Maseru - Moshoeshoe International'),
('MCW', 'USA', 'Mason City IA'),
('MVZ', 'Zimbabwe', 'Masvingo'),
('MMJ', 'Japan', 'Matsumoto, Nagano'),
('MYJ', 'Japan', 'Matsuyama'),
('MTO', 'USA', 'Mattoon (IL)'),
('MUB', 'Botswana', 'Maun'),
('MAU', 'French Polynesia', 'Maupiti'),
('MRU', 'Mauritius', 'Mauritius - S.Seewoosagur Ram International'),
('MAZ', 'Puerto Rico', 'Mayaguez'),
('MZT', 'Mexico', 'Mazatlan'),
('MFE', 'USA', 'McAllen (TX)'),
('MES', 'Indonesia', 'Medan - Polania Int l (now Soewondo AFB)'),
('KNO', 'Indonesia', 'Medan - Kualanamu International'),
('MDE', 'Colombia', 'Medellin - José María Córdova International'),
('MFR', 'USA', 'Medford (OR)'),
('MED', 'Saudi Arabia', 'Medina'),
('MKR', 'Australia', 'Meekatharra'),
('MEL', 'Australia', 'Melbourne - Melbourne Airport (Tullamarine)'),
('MLB', 'USA', 'Melbourne (FL)'),
('DOM', 'Dominica', 'Melville Hall'),
('MEM', 'USA', 'Memphis (TN)'),
('MDZ', 'Argentina', 'Mendoza'),
('MDC', 'Indonesia', 'Manado'),
('MCE', 'USA', 'Merced (CA)'),
('MID', 'Mexico', 'Merida'),
('MEI', 'USA', 'Meridian (MS)'),
('MIM', 'Australia', 'Merimbula'),
('MEZ', 'South Africa', 'Messina'),
('MTM', 'USA', 'Metlakatla (AK)'),
('MZM', 'France', 'Metz -  Frescaty'),
('ETZ', 'France', 'Metz/Nancy Metz-Nancy-Lorraine'),
('MXL', 'Mexico', 'Mexicali'),
('MEX', 'Mexico', 'Mexico City - Mexico City International Airport'),
('AZP', 'Mexico', 'Mexico City - Atizapan'),
('MEX', 'Mexico', 'Mexico City - Juarez International'),
('NLU', 'Mexico', 'Mexico City - Santa Lucia'),
('MFU', 'Zambia', 'Mfuwe'),
('MIA', 'USA', 'Miami (FL)'),
('MWD', 'Pakistan', 'Mianwali'),
('MMM', 'Australia', 'Middlemount'),
('MAF', 'USA', 'Midland/Odessa (TX)'),
('MDY', 'US Minor Outlying Islands', 'Midway Island - Sand Island Field'),
('MIK', 'Finland', 'Mikkeli'),
('MIL', 'Italy', 'Milan'),
('LIN', 'Italy', 'Milan - Linate'),
('MXP', 'Italy', 'Milan - Malpensa'),
('BGY', 'Italy', 'Milan - Orio Al Serio'),
('MQL', 'Australia', 'Mildura'),
('MLS', 'USA', 'Miles City (MT)'),
('MFN', 'New Zealand', 'Milford Sound'),
('MKE', 'USA', 'Milwaukee (WI)'),
('MTT', 'Mexico', 'Minatitlan'),
('MRV', 'Russia', 'Mineralnye Vody'),
('MSP', 'USA', 'Minneapolis - St. Paul International Airport (MN)'),
('MOT', 'USA', 'Minot (ND)'),
('MSQ', 'Belarus', 'Minsk, International'),
('MYY', 'Malaysia', 'Miri'),
('QML', 'Pakistan', 'Mirpur'),
('MSO', 'USA', 'Missula (MT)'),
('MHE', 'USA', 'Mitchell (SD)'),
('MMY', 'Japan', 'Miyako Jima (Ryuku Islands) - Hirara'),
('KMI', 'Japan', 'Miyazaki'),
('MBM', 'South Africa', 'Mkambati'),
('MFF', 'Gabon', 'Moanda'),
('MOB', 'USA', 'Mobile (AL) - Pascagoula (MS)'),
('MOD', 'USA', 'Modesto (CA)'),
('MJD', 'Pakistan', 'Moenjodaro'),
('MGQ', 'Somalia', 'Mogadishu'),
('OKU', 'Namibia', 'Mokuti'),
('MLI', 'USA', 'Moline/Quad Cities (IL)'),
('MBA', 'Kenya', 'Mombasa - Moi International'),
('MIR', 'Tunisia', 'Monastir'),
('YQM', 'Canada', 'Moncton'),
('MLU', 'USA', 'Monroe (LA)'),
('MLW', 'Liberia', 'Monrovia - Metropolitan Area'),
('ROB', 'Liberia', 'Monrovia - Roberts International'),
('MBJ', 'Jamaica', 'Montego Bay - Sangster International'),
('QGF', 'Brazil', 'Montenegro'),
('MRY', 'USA', 'Monterey (CA)'),
('MTY', 'Mexico', 'Monterrey - Gen. Mariano Escobedo'),
('NTR', 'Mexico', 'Monterrey - Aeropuerto Del Norte'),
('MVD', 'Uruguay', 'Montevideo - Carrasco International Airport'),
('MGM', 'USA', 'Montgomery (AL) - Montgomery Regional Airport'),
('MPL', 'France', 'Montpellier - Montpellier–Méditerranée Airport'),
('YMQ', 'Canada', 'Montreal'),
('YUL', 'Canada', 'Montreal - Dorval (Montréal-Trudeau)'),
('YMX', 'Canada', 'Montreal - Mirabel'),
('MTJ', 'USA', 'Montrose/Tellruide (CO)'),
('MOZ', 'French Polynesia', 'Moorea'),
('MOV', 'Australia', 'Moranbah'),
('MRZ', 'Australia', 'Moree'),
('MLM', 'Mexico', 'Morelia'),
('MGW', 'USA', 'Morgantown (WV)'),
('HNA', 'Japan', 'Morioka, Hanamaki'),
('HAH', 'Comoros (Comores)', 'Moroni - Prince Said Ibrahim'),
('MYA', 'Australia', 'Moruya'),
('MOW', 'Russia', 'Moscow - Metropolitan Area'),
('DME', 'Russia', 'Moscow - Domodedovo'),
('SVO', 'Russia', 'Moscow - Sheremetyevo'),
('VKO', 'Russia', 'Moscow - Vnukovo'),
('MWH', 'USA', 'Moses Lake (WA)'),
('MZY', 'South Africa', 'Mossel Bay'),
('OMO', 'Bosnia and Herzegovina', 'Mostar'),
('OSM', 'Iraq', 'Mosul'),
('MJL', 'Gabon', 'Mouila'),
('MQQ', 'Chad', 'Moundou'),
('GTN', 'New Zealand', 'Mount Cook'),
('MGB', 'Australia', 'Mount Gambier'),
('MMG', 'Australia', 'Mount Magnet'),
('ISA', 'Australia', 'Mt. Isa'),
('MCL', 'USA', 'Mt. McKinley (AK)'),
('MUC', 'Germany', 'Muenchen (Munich) - Franz Josef Strauss'),
('FMO', 'Germany', 'Muenster/Osnabrueck'),
('MLH', 'France', 'Mulhouse'),
('MUX', 'Pakistan', 'Multan'),
('MJV', 'Spain', 'Murcia'),
('MMK', 'Russia', 'Murmansk'),
('MSR', 'Turkey', 'Mus'),
('MCT', 'Oman', 'Muscat - Seeb'),
('MSL', 'USA', 'Muscle Shoals (AL)'),
('MKG', 'USA', 'Muskegon (MI)'),
('MFG', 'Pakistan', 'Muzaffarabad'),
('MVB', 'Gabon', 'Mvengue'),
('JMK', 'Greece', 'Mykonos'),
('MYR', 'USA', 'Myrtle Beach (SC) - Myrtle Beach AFB'),
('CRE', 'USA', 'Myrtle Beach (SC) - Grand Strand Airport'),
('MYQ', 'India', 'Mysore'),
('MJT', 'Greece', 'Mytilene (Lesbos)'),
('MZF', 'South Africa', 'Mzamba'),
('NAN', 'Fiji', 'Nadi'),
('NGS', 'Japan', 'Nagasaki'),
('NGO', 'Japan', 'Nagoya - Komaki AFB'),
('NAG', 'India', 'Nagpur'),
('NBO', 'Kenya', 'Nairobi'),
('NAJ', 'Azerbaijan', 'Nakhichevan'),
('NST', 'Thailand', 'Nakhon Si Thammarat'),
('ENC', 'France', 'Nancy'),
('YSR', 'Canada', 'Nanisivik'),
('NNG', 'Guangxi, PR China', 'Nanning'),
('NTE', 'France', 'Nantes - Nantes Atlantique Airport'),
('ACK', 'USA', 'Nantucket (MA)'),
('NAP', 'Italy', 'Naples - Naples Capodichino Airport'),
('APF', 'USA', 'Naples (FL)'),
('NAA', 'Australia', 'Narrabri'),
('NRA', 'Australia', 'Narrandera'),
('UAK', 'Greenland', 'Narsarsuaq'),
('BNA', 'USA', 'Nashville (TN)'),
('NAS', 'Bahamas', 'Nassau'),
('NAT', 'Brazil', 'Natal - Augusto Severo International Airport'),
('SUV', 'Fiji/Suva', 'Nausori'),
('WNS', 'Pakistan', 'Nawab Shah'),
('JNX', 'Greece', 'Naxos - Naxos Airport'),
('NDJ', 'Chad', 'NDjamena'),
('NLA', 'Zambia', 'NDola'),
('NSN', 'New Zealand', 'Nelson'),
('NLP', 'South Africa', 'Nelspruit'),
('MQP', 'South Africa', 'Nelspruit - Kruger Mpumalanga International Airport'),
('NEV', 'St. Kitts and Nevis', 'Nevis'),
('EWN', 'USA', 'New Bern (NC)'),
('HVN', 'USA', 'New Haven (CT)'),
('MSY', 'USA', 'New Orleans, La'),
('NQY', 'United Kingdom', 'Newquay'),
('UVL', 'Egypt', 'New Valley - Kharga'),
('JFK', 'USA', 'New York - John F. Kennedy (NY)'),
('LGA', 'USA', 'New York - LaGuardia (NY)'),
('EWR', 'USA', 'New York - Newark (NJ)'),
('NYC', 'USA', 'New York (NY)'),
('SWF', 'USA', 'Newburgh (NY)'),
('BEO', 'Australia', 'Newcastle - Belmont'),
('NTL', 'Australia', 'Newcastle - Williamtown'),
('NCL', 'United Kingdom', 'Newcastle'),
('NCS', 'South Africa', 'Newcastle'),
('ZNE', 'Australia', 'Newman'),
('PHF', 'USA', 'Newport News/Williamsburg (VA)'),
('NGE', 'Cameroon', 'N Gaoundere'),
('IAG', 'USA', 'Niagara Falls International'),
('NIM', 'Niger', 'Niamey'),
('NCE', 'France', 'Nice - Cote D Azur Airport'),
('NIC', 'Cyprus', 'Nicosia'),
('NLV', 'Ukraine', 'Nikolaev'),
('KIJ', 'Japan', 'Niigata'),
('FNI', 'France', 'Nimes'),
('INI', 'Serbia', 'Nis'),
('GOJ', 'Russia', 'Nizhny Novgorod - Strigino International Airport'),
('OME', 'USA', 'Nome (AK)'),
('NSA', 'Australia', 'Noosa'),
('NLK', 'Australia', 'Norfolk Island'),
('ORF', 'USA', 'Norfolk/Virginia Beach (VA)'),
('YVQ', 'Canada', 'Norman Wells'),
('NRK', 'Sweden', 'Norrkoeping'),
('OTH', 'USA', 'North Bend (OR)'),
('ELH', 'Bahamas', 'North Eleuthera'),
('NWI', 'United Kingdom', 'Norwich'),
('EMA', 'United Kingdom', 'Nottingham - East Midlands'),
('NDB', 'Mauritania', 'Nouadhibou'),
('NKC', 'Mauritania', 'Nouakchott'),
('NOU', 'New Caledonia', 'Noumea'),
('QND', 'Serbia', 'Novi Sad'),
('OVB', 'Russia', 'Novosibirsk - Tolmachevo Airport'),
('NUE', 'Germany', 'Nürnberg (Nuremberg)'),
('NLD', 'Mexico', 'Nuevo Laredo'),
('TBU', 'Tonga', 'Nukualofa - FuaAmotu International'),
('OAK', 'USA', 'Oakland (CA)'),
('OAX', 'Mexico', 'Oaxaca - Xoxocotlan'),
('ODE', 'Denmark', 'Odense'),
('ODS', 'Ukraine', 'Odessa'),
('ORB', 'Sweden', 'Oerebro'),
('OHD', 'Macedonia', 'Ohrid'),
('OIT', 'Japan', 'Oita'),
('OKJ', 'Japan', 'Okayama'),
('OKA', 'Japan', 'Okinawa, Ryukyo Island - Naha'),
('OKC', 'USA', 'Oklahoma City (OK) - Will Rogers World'),
('OLB', 'Italy', 'Olbia'),
('OLP', 'Australia', 'Olympic Dam'),
('OMA', 'USA', 'Omaha (NE)'),
('OND', 'Namibia', 'Ondangwa'),
('ONT', 'USA', 'Ontario (CA)'),
('ORN', 'Algeria', 'Oran (Ouahran)'),
('OAG', 'Australia', 'Orange'),
('SNA', 'USA', 'Orange County (Santa Ana) (CA)'),
('OMD', 'Namibia', 'Oranjemund'),
('AUA', 'Aruba', 'Oranjestad - Reina Beatrix International'),
('KOI', 'United Kingdom', 'Orkney - Kirkwall'),
('ORL', 'USA', 'Orlando Metropolitan Area (FL)'),
('MCO', 'USA', 'Orlando - International Airport (FL)'),
('ORS', 'Australia', 'Orpheus Island'),
('OSA', 'Japan', 'Osaka, Metropolitan Area'),
('ITM', 'Japan', 'Osaka - Itami'),
('KIX', 'Japan', 'Osaka - Kansai International Airport'),
('OSH', 'USA', 'Oshkosh (WI)'),
('OSI', 'Croatia (Hrvatska)', 'Osijek'),
('OSL', 'Norway', 'Oslo - Oslo Airport, Gardermoen'),
('FBU', 'Norway', 'Oslo - Fornebu'),
('TRF', 'Norway', 'Oslo - Sandefjord'),
('YOW', 'Canada', 'Ottawa - Hull'),
('ODA', 'Central African Republic', 'Ouadda'),
('OZZ', 'Morocco', 'Ouarzazate'),
('OUH', 'South Africa', 'Oudtshoorn'),
('OUA', 'Burkina Faso', 'Ouagadougou'),
('OUD', 'Morocco', 'Oujda'),
('OUL', 'Finland', 'Oulu'),
('OUK', 'United Kingdom', 'Out Skerries (Shetland)'),
('OVD', 'Spain', 'Oviedo'),
('OWB', 'USA', 'Owensboro (KY)'),
('OXR', 'USA', 'Oxnard (CA)'),
('UVE', 'Gabon/Loyautte', 'Oyem'),
('PAD', 'Germany', 'Paderborn/Lippstadt'),
('PAH', 'USA', 'Paducah (KY)'),
('PGA', 'USA', 'Page/Lake Powell (AZ)'),
('PPG', 'American Samoa', 'Pago Pago'),
('PKB', 'USA', 'Pakersburg (WV) /Marietta (OH)'),
('PMO', 'Italy', 'Palermo - Punta Raisi'),
('PMI', 'Spain', 'Palma de Mallorca'),
('PMW', 'Brazil', 'Palmas'),
('PMD', 'USA', 'Palmdale/Lancaster (CA)'),
('PMR', 'New Zealand', 'Palmerston North'),
('PSP', 'USA', 'Palm Springs (CA)'),
('PTY', 'Panama', 'Panama City - Tocumen International'),
('PFN', 'USA', 'Panama City (FL)'),
('PJG', 'Pakistan', 'Panjgur'),
('PNL', 'Italy', 'Pantelleria'),
('PPT', 'French Polynesia (Tahiti)', 'Papeete - Faaa'),
('PFO', 'Cyprus', 'Paphos'),
('PBO', 'Australia', 'Paraburdoo'),
('PBM', 'Suriname', 'Paramaribo - Zanderij International'),
('PAR', 'France', 'Paris'),
('CDG', 'France', 'Paris - Charles de Gaulle'),
('LBG', 'France', 'Paris - Le Bourget'),
('ORY', 'France', 'Paris - Orly'),
('PBH', 'Bhutan', 'Paro'),
('PSC', 'USA', 'Pasco (WA)'),
('PSI', 'Pakistan', 'Pasni'),
('PAT', 'India', 'Patna'),
('PYX', 'Thailand', 'Pattaya'),
('PUF', 'France', 'Pau'),
('PLN', 'USA', 'Pellston (MI)'),
('PEN', 'Malaysia', 'Penang International'),
('PDT', 'USA', 'Pendelton (OR)'),
('PNS', 'USA', 'Pensacola (FL)'),
('PIA', 'USA', 'Peoria/Bloomington (IL)'),
('PEI', 'Colombia', 'Pereira'),
('PGF', 'France', 'Perpignan'),
('PER', 'Australia', 'Perth International'),
('PEG', 'Italy', 'Perugia'),
('PSR', 'Italy', 'Pescara'),
('PEW', 'Pakistan', 'Peshawar'),
('PSG', 'USA', 'Petersburg (AK)'),
('PHW', 'South Africa', 'Phalaborwa'),
('PHL', 'USA', 'Philadelphia (PA) - International'),
('PNH', 'Cambodia', 'Phnom Penh - Pochentong'),
('PHX', 'USA', 'Phoenix (AZ) - Sky Harbor International'),
('HKT', 'Thailand', 'Phuket'),
('PIR', 'USA', 'Pierre (SD)'),
('PZB', 'South Africa', 'Pietermaritzburg'),
('PTG', 'South Africa', 'Pietersburg'),
('NTY', 'South Africa', 'Pilanesberg/Sun City'),
('PSA', 'Italy', 'Pisa - Galileo Galilei'),
('PIT', 'USA', 'Pittsburgh International Airport (PA)'),
('PLB', 'USA', 'Plattsburgh (NY)'),
('PBZ', 'South Africa', 'Plettenberg Bay'),
('PIH', 'USA', 'Pocatello (ID)'),
('TGD', 'Montenegro', 'Podgorica'),
('PNI', 'Micronesia', 'Pohnpei'),
('PTP', 'Guadeloupe', 'Pointe a Pitre'),
('PNR', 'Congo (ROC)', 'Pointe Noire'),
('PIS', 'France', 'Poitiers - Biard'),
('PSE', 'Puerto Rico', 'Ponce'),
('PDL', 'Portugal', 'Ponta Delgada'),
('POR', 'Finland', 'Pori'),
('CLM', 'USA', 'Port Angeles (WA)'),
('PAP', 'Haiti', 'Port au Prince'),
('PUG', 'Australia', 'Port Augusta'),
('PLZ', 'South Africa', 'Port Elizabeth'),
('POG', 'Gabon', 'Port Gentil'),
('PHC', 'Nigeria', 'Port Harcourt'),
('PHE', 'Australia', 'Port Hedland'),
('PTJ', 'Australia', 'Portland'),
('PWM', 'USA', 'Portland (ME)'),
('PDX', 'USA', 'Portland International (OR)'),
('PLO', 'Australia', 'Port Lincoln'),
('PQQ', 'Australia', 'Port Macquarie'),
('YPN', 'Canada', 'Port Menier, PQ'),
('POM', 'Papua New Guinea', 'Port Moresby - Jackson Field'),
('OPO', 'Portugal', 'Porto'),
('POA', 'Brazil', 'Porto Alegre - Salgado Filho International Airport'),
('POS', 'Trinidad and Tobago', 'Port of Spain - Piarco International'),
('PSD', 'Egypt', 'Port Said'),
('PXO', 'Portugal', 'Porto Santo'),
('PVH', 'Brazil', 'Porto Velho'),
('VLI', 'Vanuatu', 'Port Vila'),
('POU', 'USA', 'Poughkeepsie (NY)'),
('POZ', 'Poland', 'Poznan, Lawica'),
('PRG', 'Czech Republic', 'Prague - Václav Havel Airport (formerly Ruzyne)'),
('RAI', 'Cape Verde', 'Praia - Nelson Mandela International Airport'),
('PQI', 'USA', 'Presque Island (ME)'),
('PRY', 'South Africa', 'Pretoria - Wonderboom Apt.'),
('PVK', 'Greece', 'Preveza/Lefkas'),
('YXS', 'Canada', 'Prince George'),
('YPR', 'Canada', 'Prince Rupert/Digby Island'),
('PRN', 'Serbia', 'Pristina'),
('PPP', 'Australia', 'Prosperpine'),
('PVD', 'USA', 'Providence (RI)'),
('SCC', 'USA', 'Prudhoe Bay (AK)'),
('PBC', 'Mexico', 'Puebla'),
('PUB', 'USA', 'Pueblo (CO)'),
('PXM', 'Mexico', 'Puerto Escondido'),
('PZO', 'Venezuela', 'Puerto Ordaz'),
('POP', 'Dominican Republic', 'Puerto Plata'),
('PVR', 'Mexico', 'Puerto Vallarta'),
('XPK', 'Canada', 'Pukatawagan'),
('PUY', 'Croatia (Hrvatska)', 'Pula'),
('PUW', 'USA', 'Pullman (WA)'),
('PNQ', 'India, Maharashtra', 'Pune'),
('PUQ', 'Chile', 'Punta Arenas - Presidente Carlos Ibáñez del Campo'),
('PUJ', 'Dominican Republic', 'Punta Cana - Punta Cana International'),
('PUS', 'South Korea', 'Pu San (Busan) - Gimhae International Airport'),
('FNJ', 'North Korea', 'Pyongyang - Sunan International Airport'),
('YQB', 'Canada', 'Quebec - Quebec International'),
('UEE', 'Australia', 'Queenstown'),
('ZQN', 'New Zealand', 'Queenstown'),
('UET', 'Pakistan', 'Quetta'),
('TAO', 'Shandong, PR China', 'Qingdao'),
('UIP', 'France', 'Quimper'),
('UIN', 'USA', 'Quincy (IL)'),
('UIO', 'Ecuador', 'Quito - Mariscal Sucre International Airport'),
('RBA', 'Morocco', 'Rabat - Rabat-Salé Airport'),
('RYK', 'Pakistan', 'Rahim Yar Khan - Shaikh Zayed International Airport'),
('RFP', 'French Polynesia', 'Raiatea'),
('YOP', 'Canada', 'Rainbow Lake, AB'),
('RAJ', 'India', 'Rajkot'),
('RDU', 'USA', 'Raleigh/Durham (NC)'),
('IXR', 'India', 'Ranchi'),
('RGI', 'French Polynesia', 'Rangiroa'),
('RGN', 'Myanmar', 'Rangoon (Yangon) - Mingaladon'),
('RAP', 'USA', 'Rapid City (SD)'),
('RAR', 'Cook Island', 'Rarotonga'),
('RKT', 'United Arab Emirates', 'Ras al Khaymah (Ras al Khaimah)'),
('RAZ', 'Pakistan', 'Rawala Kot'),
('RWP', 'Pakistan', 'Rawalpindi'),
('RDG', 'USA', 'Reading (PA)'),
('REC', 'Brazil', 'Recife - Guararapes-Gilberto Freyre International'),
('RDD', 'USA', 'Redding (CA)'),
('RDM', 'USA', 'Redmond (OR)'),
('REG', 'Italy', 'Reggio Calabria'),
('YQR', 'Canada', 'Regina'),
('TFS', 'Teneriffa/Spain', 'Reina Sofia'),
('RNS', 'France', 'Rennes'),
('RNO', 'USA', 'Reno (NV)'),
('YRB', 'Canada', 'Resolute Bay'),
('REU', 'Spain', 'Reus'),
('REK', 'Iceland', 'Reykjavik - Metropolitan Area'),
('KEF', 'Iceland', 'Reykjavik - Keflavik International'),
('RHI', 'USA', 'Rhinelander (WI)'),
('RHO', 'Greece', 'Rhodos'),
('RCB', 'South Africa', 'Richards Bay'),
('RIC', 'USA', 'Richmond (VA)'),
('RIX', 'Latvia', 'Riga'),
('RJK', 'Croatia (Hrvatska)', 'Rijeka'),
('RMI', 'Italy', 'Rimini'),
('RBR', 'Brazil', 'Rio Branco - Plácido de Castro International Airport'),
('GIG', 'Brazil', 'Rio de Janeiro - Galeao'),
('SDU', 'Brazil', 'Rio de Janeiro - Santos Dumont'),
('RIO', 'Brazil', 'Rio de Janeiro'),
('RUH', 'Saudi Arabia', 'Riyadh - King Khaled International'),
('RNE', 'France', 'Roanne'),
('ROA', 'USA', 'Roanoke (VA)'),
('RTB', 'Honduras', 'Roatan'),
('RST', 'USA', 'Rochester (MN)'),
('ROC', 'USA', 'Rochester (NY)'),
('RSD', 'Bahamas', 'Rock Sound'),
('RKS', 'USA', 'Rock Springs (WY)'),
('RFD', 'USA', 'Rockford (IL)'),
('ROK', 'Australia', 'Rockhampton'),
('RKD', 'USA', 'Rockland (ME)'),
('RWI', 'USA', 'Rocky Mount - Wilson (NC)'),
('RDZ', 'France', 'Rodez'),
('RRG', 'Mauritius', 'Rodrigues Island'),
('RNN', 'Denmark', 'Roenne'),
('ROM', 'Italy', 'Rome'),
('CIA', 'Italy', 'Rome - Ciampino'),
('FCO', 'Italy', 'Rome - Fuimicino'),
('RNB', 'Sweden', 'Ronneby'),
('ROS', 'Argentina', 'Rosario'),
('RVI', 'Russia', 'Rostov-on-Don - Rostov-on-Don Airport'),
('ROV', 'Russia', 'Rostov-on-Don - Platov International Airport'),
('ROT', 'New Zealand', 'Rotorua'),
('RTM', 'Netherlands', 'Rotterdam'),
('RVN', 'Finland', 'Rovaniemi'),
('NDU', 'Namibia', 'Rundu'),
('ROU', 'Bulgaria', 'Ruse'),
('SCN', 'Germany', 'Saarbruecken'),
('SMF', 'USA', 'Sacramento (CA)'),
('SDS', 'Japan', 'Sado Shima'),
('MBS', 'USA', 'Saginaw/Bay City/Midland (MI)'),
('SDT', 'Pakistan', 'Saidu Sharif'),
('SGN', 'Viet Nam', 'Saigon (Ho Chi Minh City) - Tan Son Nhat International'),
('SBK', 'France', 'Saint Brieuc'),
('RUN', 'Reunion', 'Saint Denis - Roland Garros Airport'),
('YSJ', 'Canada', 'Saint John'),
('SPN', 'Northern Mariana Islands', 'Saipan'),
('SID', 'Cape Verde', 'Sal'),
('SLL', 'Oman', 'Salalah'),
('SLE', 'USA', 'Salem (OR)'),
('SNS', 'USA', 'Salinas (CA)'),
('SNC', 'Ecuador', 'Salinas'),
('SAY', 'Zimbabwe', 'Salisbury'),
('SBY', 'USA', 'Salisbury (MD)'),
('SKG', 'Greece', 'Saloniki'),
('SLA', 'Argentina', 'Salta, Gen Belgrano'),
('SLC', 'USA', 'Salt Lake City (UT)'),
('SSA', 'Brazil', 'Salvador - Salvador International Airport'),
('SZG', 'Austria', 'Salzburg - W.A. Mozart'),
('KUF', 'Russia', 'Samara - Kurumoch International Airport'),
('SKD', 'Uzbekistan', 'Samarkand - Samarkand International Airport'),
('SMI', 'Greece', 'Samos'),
('SZF', 'Turkey', 'Samsun'),
('ADZ', 'Colombia', 'San Andres'),
('SJT', 'USA', 'San Angelo (TX)'),
('SAT', 'USA', 'San Antonio (TX)'),
('BRC', 'Argentina', 'San Carlos de Bariloche'),
('SAN', 'USA', 'San Diego - Lindberg Field International (CA)'),
('SFO', 'USA', 'San Francisco - International Airport, SA'),
('SJD', 'Mexico', 'San Jose Cabo'),
('SJO', 'Costa Rica', 'San Jose'),
('SJC', 'USA', 'San Jose (CA)'),
('SJU', 'Puerto Rico', 'San Juan - Luis Munoz Marin International Airport'),
('SBP', 'USA', 'San Luis Obisco (CA)'),
('SLP', 'Mexico', 'San Luis Potosi'),
('SPY', 'Cote d Ivoire', 'San Pedro'),
('SAP', 'Honduras', 'San Pedro Sula'),
('ZSA', 'Bahamas', 'San Salvador'),
('SAL', 'El Salvador', 'San Salvador'),
('EAS', 'Spain', 'San Sebastian'),
('SAH', 'Yemen', 'Sanaa (Sanaa) - Sanaa International'),
('YZP', 'Canada', 'Sandspit'),
('SNA', 'USA', 'Santa Ana - John Wayne Airport (CA)'),
('SBA', 'USA', 'Santa Barbara (CA)'),
('SPC', 'Spain', 'Santa Cruz de la Palma'),
('SRZ', 'Bolivia', 'Santa Cruz de la Sierra'),
('SKV', 'Egypt', 'Santa Katarina - Mount Sinai'),
('SMA', 'Portugal', 'Santa Maria'),
('SMX', 'USA', 'Santa Maria (CA)'),
('SDR', 'Spain', 'Santander'),
('STS', 'USA', 'Santa Rosa (CA)'),
('SRB', 'Bolivia', 'Santa Rosa'),
('SRA', 'Brazil', 'Santa Rosa'),
('RSA', 'Argentina', 'Santa Rosa'),
('SDH', 'Honduras', 'Santa Rosa, Copan'),
('SSL', 'Colombia', 'Santa Rosalia'),
('SRL', 'Mexico', 'Santa Rosalia'),
('SCU', 'Cuba', 'Santiago - Antonio Maceo Airport'),
('SCL', 'Chile', 'Santiago de Chile - Arturo Merino Benitez'),
('SCQ', 'Spain', 'Santiago de Compostela'),
('SON', 'Vanuatu', 'Santo'),
('SDQ', 'Dominican Republic', 'Santo Domingo'),
('SLZ', 'Brazil', 'Sao Luis - Marechal Cunha Machado International'),
('SAO', 'Brazil', 'Sao Paulo'),
('CGH', 'Brazil', 'Sao Paulo - Congonhas'),
('GRU', 'Brazil', 'Sao Paulo - Guarulhos'),
('VCP', 'Brazil', 'Sao Paulo - Viracopos'),
('TMS', 'Sao Tome & Principe', 'Sao Tome'),
('SPK', 'Hokkaido, Japan', 'Sapporo'),
('OKD', 'Hokkaido, Japan', 'Sapporo - Okadama'),
('CTS', 'Japan', 'Sapporo - New Chitose Airport'),
('SJJ', 'Bosnia and Herzegovina', 'Sarajevo'),
('SKX', 'Russia', 'Saransk - Saransk Airport'),
('SRQ', 'USA', 'Sarasota/Bradenton (FL)'),
('YXE', 'Canada', 'Saskatoon'),
('ZSS', 'Cote d Ivoire', 'Sassandra'),
('SAV', 'USA', 'Savannah (GA)'),
('SVL', 'Finland', 'Savonlinna'),
('TAB', 'Trinidad and Tobago', 'Scarborough - Crown Point International'),
('NSO', 'Australia', 'Scone'),
('SCF', 'USA', 'Scottsdale (AZ)'),
('SEA', 'USA', 'Seattle/Tacoma (WA)'),
('SEB', 'Libya', 'Sehba'),
('SJY', 'Finland', 'Seinaejoki'),
('PKW', 'Botswana', 'Selibi Phikwe'),
('SDJ', 'Japan', 'Sendai'),
('ICN', 'South Korea', 'Seoul - Incheon International Airport'),
('SEL', 'South Korea', 'Seoul - Kimpo'),
('SVQ', 'Spain', 'Sevilla'),
('SFA', 'Tunisia', 'Sfax'),
('ZTM', 'Canada', 'Shamattawa, MB'),
('SHA', 'China', 'Shanghai - Hongqiao'),
('PVG', 'China', 'Shanghai - Pu Dong'),
('SNN', 'Ireland', 'Shannon (Limerick)'),
('SHJ', 'United Arab Emirates', 'Sharjah'),
('SSH', 'Egypt', 'Sharm El Sheikh'),
('SZD', 'United Kingdom', 'Sheffield, City Airport'),
('DSA', 'United Kingdom', 'Sheffield, Doncaster, Robin Hood International Airport'),
('SHD', 'USA', 'Shenandoah Valley/Stauton (VA)'),
('SHE', 'Liaoning, PR China', 'Shenyang'),
('SZX', 'Guangdong, PR China', 'Shenzhen - Shenzhen Bao an International'),
('SHR', 'USA', 'Sheridan (WY)'),
('SHV', 'USA', 'Shreveport, La'),
('JHQ', 'Australia', 'Shute Harbour'),
('SBW', 'Malaysia', 'Sibu'),
('SDY', 'USA', 'Sidney (MT)'),
('SLS', 'Bulgaria', 'Silistra'),
('SIP', 'Ukraine', 'Simferopol'),
('MPD', 'Pakistan', 'Sindhri'),
('SIN', 'Singapore', 'Singapore - Changi'),
('QPG', 'Singapore', 'Singapore - Paya Lebar'),
('XSP', 'Singapore', 'Singapore - Seletar'),
('SIX', 'Australia', 'Singleton'),
('SUX', 'USA', 'Sioux City IA'),
('FSD', 'USA', 'Sioux Falls (SD)'),
('SIS', 'South Africa', 'Sishen'),
('SIT', 'USA', 'Sitka (AK)'),
('VAS', 'Turkey', 'Sivas'),
('SEW', 'Egypt', 'Siwa'),
('SGY', 'USA', 'Skagway (AK)'),
('KDU', 'Pakistan', 'Skardu'),
('JSI', 'Greece', 'Skiathos'),
('SKP', 'Macedonia', 'Skopje'),
('SKS', 'Denmark', 'Skrydstrup'),
('SZK', 'South Africa', 'Skukuza'),
('SXL', 'Ireland', 'Sligo'),
('YYD', 'Canada', 'Smithers'),
('SOT', 'Finland', 'Sodankylae'),
('SGD', 'Denmark', 'Soenderborg'),
('SFJ', 'Greenland', 'Soendre Stroemfjord'),
('SOF', 'Bulgaria', 'Sofia - Vrazhdebna'),
('SOG', 'Norway', 'Sogndal'),
('SOU', 'United Kingdom', 'Southampton - Eastleigh'),
('SBN', 'USA', 'South Bend (IN)'),
('XSI', 'Canada', 'South Indian Lake, MB'),
('SOI', 'Australia', 'South Molle Island'),
('SEN', 'United Kingdom', 'Southend (London)'),
('SPU', 'Croatia (Hrvatska)', 'Split'),
('GEG', 'USA', 'Spokane (WA)'),
('SBU', 'South Africa', 'Springbok'),
('SPI', 'USA', 'Springfield (IL)'),
('SGF', 'USA', 'Springfield (MO)'),
('SXR', 'India', 'Srinagar'),
('YIF', 'Canada', 'St. Augustin, PQ'),
('STX', 'Virgin Islands (U.S.)', 'St. Croix'),
('EBU', 'France', 'St. Etienne'),
('SGU', 'USA', 'St. George (UT)'),
('YYT', 'Canada', 'St. Johns'),
('SKB', 'St. Kitts and Nevis', 'St. Kitts'),
('STL', 'USA', 'St. Louis (MO) Lambert–St. Louis International Airport'),
('UVF', 'Saint Lucia', 'St. Lucia Hewanorra'),
('SLU', 'Saint Lucia', 'St. Lucia Vigle'),
('SXM', 'Netherlands Antilles', 'St. Marteen'),
('SFG', 'St. Martin (Guadeloupe)', 'St. Martin'),
('LED', 'Russia', 'St. Petersburg (Leningrad) - Pulkovo'),
('FSP', 'Canada', 'St. Pierre, NF'),
('STT', 'Virgin Islands (U.S.)', 'St. Thomas'),
('SVD', 'Saint Vincent and the Grenadines', 'St. Vincent'),
('STN', 'United Kingdom', 'Stansted (London)'),
('SCE', 'USA', 'State College/Belefonte (PA)'),
('SVG', 'Norway', 'Stavanger'),
('HDN', 'USA', 'Steamboat Springs (CO)'),
('SZZ', 'Poland', 'Stettin'),
('STO', 'Sweden', 'Stockholm Metropolitan Area'),
('ARN', 'Sweden', 'Stockholm - Arlanda'),
('BMA', 'Sweden', 'Stockholm - Bromma'),
('SCK', 'USA', 'Stockton (CA)'),
('SYY', 'United Kingdom', 'Stornway'),
('SXB', 'France', 'Strasbourg - Strasbourg Airport'),
('KBY', 'Australia', 'Streaky Bay'),
('STR', 'Germany', 'Stuttgart - Echterdingen'),
('SUL', 'Pakistan', 'Sui'),
('SKZ', 'Pakistan', 'Sukkur'),
('LSI', 'United Kingdom', 'Sumburgh (Shetland)'),
('SUN', 'USA', 'Sun Valley (ID)'),
('SDL', 'Sweden', 'Sundsvall'),
('MCY', 'Australia', 'Sunshine Coast'),
('SUB', 'Indonesia', 'Surabaya - Juanda'),
('STV', 'India', 'Surat'),
('SUV', 'Fiji', 'Suva - Nausori Airport (Luvuluvu)'),
('SWP', 'Namibia', 'Swakopmund'),
('SYD', 'Australia', 'Sydney - Sydney Airport'),
('ZYL', 'Bangladesh', 'Sylhet'),
('SYR', 'USA', 'Syracuse (NY)'),
('TUU', 'Saudi Arabia', 'Tabuk'),
('TIF', 'Saudi Arabia', 'Taif'),
('TPE', 'Taiwan', 'Taipei - Chiang Kai Shek'),
('TAY', 'Taiwan', 'Taipei - Sung Shan'),
('TYN', 'Shanxi, PR China', 'Taiyuan'),
('TAK', 'Japan', 'Takamatsu'),
('TKA', 'USA', 'Talkeetna (AK)'),
('TLH', 'USA', 'Tallahassee (FL)'),
('QUF', 'Estonia', 'Tallinn - Pirita Harbour'),
('TLL', 'Estonia', 'Tallinn - Ulemiste'),
('TPA', 'USA', 'Tampa - International (FL)'),
('TMP', 'Finland', 'Tampere'),
('TAM', 'Mexico', 'Tampico - Gen. F. Javier Mina'),
('TMW', 'Australia', 'Tamworth'),
('TNG', 'Morocco', 'Tangier - Boukhalef'),
('TRO', 'Australia', 'Taree'),
('TGV', 'Bulgaria', 'Targovishte'),
('TAS', 'Uzbekistan', 'Tashkent - International'),
('TWU', 'Malaysia', 'Tawau'),
('TBS', 'Georgia', 'Tbilisi - Novo Alexeyevka'),
('TEU', 'New Zealand', 'Te Anau'),
('MME', 'United Kingdom', 'Teesside, Durham Tees Valley'),
('TGU', 'Honduras', 'Tegucigalpa'),
('THR', 'Iran', 'Tehran (Teheran) - Mehrabad'),
('TEQ', 'Turkey', 'Tekirdag - Corlu'),
('TLV', 'Israel', 'Tel Aviv - Ben Gurion International'),
('TEX', 'USA', 'Telluride (CO)'),
('TEM', 'Australia', 'Temora'),
('TCI', 'Spain', 'Tenerife'),
('TFS', 'Spain', 'Tenerife - Sur Reina Sofia'),
('TFN', 'Spain', 'Tenerife - Norte Los Rodeos'),
('TCA', 'Australia', 'Tennant Creek'),
('TER', 'Portugal', 'Terceira'),
('THE', 'Brazil', 'Teresina'),
('TMZ', 'Uzbekistan', 'Termez (Termes)'),
('YXT', 'Canada', 'Terrace'),
('HUF', 'USA', 'Terre Haute (IN)'),
('TXK', 'USA', 'Texarkana (AR)'),
('TCU', 'South Africa', 'Thaba Nchu'),
('YQD', 'Canada', 'The Pas'),
('SKG', 'Greece', 'Thessaloniki - Makedonia Apt.'),
('TVF', 'USA', 'Thief River Falls (MN)'),
('JTR', 'Greece', 'Thira'),
('TRV', 'India', 'Thiruvananthapuram'),
('TED', 'Denmark', 'Thisted'),
('YTH', 'Canada', 'Thompson'),
('KTB', 'USA', 'Thorne Bay (AK)'),
('YQT', 'Canada', 'Thunder Bay'),
('TIS', 'Australia', 'Thursday Island'),
('TSN', 'China', 'Tianjin'),
('TIJ', 'Mexico', 'Tijuana - Rodriguez'),
('TOD', 'Indonesia', 'Tioman'),
('TIA', 'Albania', 'Tirana - Rinas'),
('TRZ', 'India', 'Tiruchirapally'),
('TIV', 'Montenegro', 'Tivat'),
('TAB', 'Trinidad and Tobago', 'Tobago'),
('TKS', 'Japan', 'Tokushima'),
('TYO', 'Japan', 'Tokyo'),
('HND', 'Japan', 'Tokyo - Haneda'),
('NRT', 'Japan', 'Tokyo - Narita'),
('TOL', 'USA', 'Toledo (OH)'),
('TPR', 'Australia', 'Tom Price'),
('TWB', 'Australia', 'Toowoomba'),
('YTZ', 'Canada', 'Toronto - Billy Bishop Toronto City Airport'),
('YYZ', 'Canada', 'Toronto - Toronto Pearson International Airport'),
('YTO', 'Canada', 'Toronto'),
('TOV', 'British Virgin Islands', 'Tortola'),
('TOU', 'New Caledonia', 'Touho'),
('TLS', 'France', 'Toulouse - Blagnac Airport'),
('TSV', 'Australia', 'Townsville'),
('TOY', 'Japan', 'Toyama'),
('TZX', 'Turkey', 'Trabzon'),
('TPS', 'Italy', 'Trapani'),
('TVC', 'USA', 'Traverse City (MI)'),
('TCB', 'Bahamas', 'Treasure Cay'),
('TTN', 'USA', 'Trenton/Princeton (NJ)'),
('TSF', 'Italy', 'Treviso'),
('TRI', 'USA', 'Tri-Cities Regional (TN) /VA'),
('TRS', 'Italy', 'Trieste'),
('TIP', 'Libya', 'Tripoli - Tripoli International'),
('TOS', 'Norway', 'Tromsoe'),
('TRD', 'Norway', 'Trondheim'),
('TSB', 'Namibia', 'Tsumeb'),
('TUS', 'USA', 'Tucson (AZ)'),
('TUP', 'USA', 'Tulepo (MS)'),
('TUL', 'USA', 'Tulsa (OK)'),
('TUN', 'Tunisia', 'Tunis - Carthage'),
('TUK', 'Pakistan', 'Turbat'),
('TRN', 'Italy', 'Turin'),
('TKU', 'Finland', 'Turku'),
('TCL', 'USA', 'Tuscaloosa (AL)'),
('TGZ', 'Mexico', 'Tuxtla Gutierrez'),
('TWF', 'USA', 'Twin Falls (ID)'),
('TYR', 'USA', 'Tyler (TX)'),
('UAH', 'French Polynesia', 'Ua Huka'),
('UAP', 'French Polynesia', 'Ua Pou'),
('UBJ', 'Japan', 'Ube'),
('UBA', 'Brazil', 'Uberaba'),
('UDI', 'Brazil', 'Uberlandia - Eduardo Gomes Airport'),
('UBP', 'Thailand', 'Ubon Ratchathani - Muang Ubon Airport'),
('UDR', 'India', 'Udaipur - Dabok Airport'),
('UDE', 'Netherlands', 'Uden - Volkel Airport'),
('UTH', 'Thailand', 'Udon Thani'),
('UFA', 'Russia', 'Ufa'),
('UHE', 'Czech Republic', 'Uherske Hradiste'),
('UGO', 'Angola', 'Uige'),
('UPG', 'Indonesia', 'Ujung Pandang - Hasanudin Airport'),
('UCT', 'Russia', 'Ukhta'),
('UKI', 'USA', 'Ukiah (CA)'),
('ULN', 'Mongolia', 'Ulaanbaatar - Buyant Uhaa Airport'),
('UUD', 'Russia', 'Ulan-Ude'),
('HLH', 'PR China', 'Ulanhot'),
('ULB', 'Vanuatu', 'Ulei'),
('USN', 'South Korea', 'Ulsan'),
('ULD', 'South Africa', 'Ulundi'),
('UME', 'Sweden', 'Umea'),
('YUD', 'Canada', 'Umiujaq'),
('UTT', 'South Africa', 'Umtata'),
('UNK', 'USA', 'Unalakleet (AK)'),
('UNI', 'Saint Vincent and the Grenadines', 'Union Island'),
('UNT', 'United Kingdom', 'Unst (Shetland Island) - Baltasound Airport'),
('UPL', 'Costa Rica', 'Upala'),
('JUV', 'Greenland', 'Upernavik - Upernavik Heliport'),
('UTN', 'South Africa', 'Upington'),
('UPP', 'USA', 'Upolu Point (HI)'),
('YBE', 'Canada', 'Uranium City'),
('UGC', 'Uzbekistan', 'Urgench'),
('URM', 'Venezuela', 'Uriman'),
('OMH', 'Iran', 'Urmiehm (Orumieh)'),
('UPN', 'Mexico', 'Uruapan'),
('URB', 'Brazil', 'Urubupunga - Ernesto Pochler Airport'),
('URG', 'Brazil', 'Uruguaiana - Ruben Berta Airport'),
('URC', 'Xinjiang, PR China', 'Urumqi'),
('URZ', 'Afghanistan', 'Uruzgan'),
('USH', 'Argentina', 'Ushuaia - Islas Malvinas Airport'),
('UTP', 'Thailand', 'Utapao (Pattaya)'),
('UCA', 'USA', 'Utica (NY) - Oneida County Airport'),
('UII', 'Honduras', 'Utila'),
('UMD', 'Greenland', 'Uummannaq'),
('UDJ', 'Ukraine', 'Uzhgorod'),
('VAA', 'Finland', 'Vaasa'),
('VXO', 'Sweden', 'Vaexjoe'),
('EGE', 'USA', 'Vail (CO)'),
('YVO', 'Canada', 'Val d Or'),
('VDZ', 'USA', 'Valdez (AK)'),
('VLD', 'USA', 'Valdosta (GA)'),
('VLC', 'Spain', 'Valencia'),
('VLN', 'Venezuela', 'Valencia'),
('VLL', 'Spain', 'Valladolid'),
('VAP', 'Chile', 'Valparaiso'),
('VDE', 'Spain', 'Valverde'),
('VAN', 'Turkey', 'Van - Ferit Melen'),
('YVR', 'Canada', 'Vancouver - Vancouver International'),
('VRA', 'Cuba', 'Varadero'),
('VNS', 'India', 'Varanasi'),
('VRK', 'Finland', 'Varkaus'),
('VAR', 'Bulgaria', 'Varna'),
('VST', 'Sweden', 'Vasteras'),
('VLU', 'Russia', 'Velikiye Luki (Welikije Luki)'),
('VCE', 'Italy', 'Venice - Marco Polo'),
('VER', 'Mexico', 'Veracruz'),
('VEL', 'USA', 'Vernal (UT)'),
('VRB', 'USA', 'Vero Beach/Ft. Pierce (FL)'),
('VBS', 'Italy', 'Verona (Brescia) Montichiari'),
('VRN', 'Italy', 'Verona'),
('YYJ', 'Canada', 'Victoria'),
('VFA', 'Zimbabwe', 'Victoria Falls'),
('VID', 'Bulgaria', 'Vidin'),
('VTE', 'Lao PDR', 'Vientiane - Wattay'),
('VGO', 'Spain', 'Vigo'),
('VSA', 'Mexico', 'Villahermosa'),
('VNO', 'Lithuania', 'Vilnius'),
('VIJ', 'Virgin Islands (British)', 'Virgin Gorda'),
('VIS', 'USA', 'Visalia (CA)'),
('VBY', 'Sweden', 'Visby'),
('VIT', 'Spain', 'Vitoria'),
('VIX', 'Brazil', 'Vitoria - Eurico de Aguiar Salles Airport'),
('VYD', 'South Africa', 'Vryheid'),
('YWK', 'Canada', 'Wabush'),
('ACT', 'USA', 'Waco (TX)'),
('WGA', 'Australia', 'Wagga'),
('ALW', 'USA', 'Walla Walla (WA)'),
('WLS', 'Wallis and Futuna Islands', 'Wallis'),
('WVB', 'South Africa', 'Walvis Bay'),
('WMB', 'Australia', 'Warrnambool'),
('WAW', 'Poland', 'Warsaw - Frédéric Chopin'),
('BWI', 'USA', 'Washington DC - Baltimore Washington International'),
('IAD', 'USA', 'Washington DC - Dulles International'),
('DCA', 'USA', 'Washington DC - Ronald Reagan National'),
('WAS', 'USA', 'Washington DC'),
('ALO', 'USA', 'Waterloo IA'),
('ATY', 'USA', 'Watertown (SD)'),
('CWA', 'USA', 'Wausau/Stevens Point (WI)'),
('WEI', 'Australia', 'Weipa'),
('WEL', 'South Africa', 'Welkom'),
('WLG', 'New Zealand', 'Wellington'),
('EAT', 'USA', 'Wenatchee (WA)'),
('PBI', 'USA', 'West Palm Beach (FL)'),
('WYS', 'USA', 'West Yellowstone (MT)'),
('GWT', 'Germany', 'Westerland, Sylt Airport'),
('WHK', 'New Zealand', 'Whakatane'),
('YXN', 'Canada', 'Whale Cove, NT'),
('WRE', 'New Zealand', 'Whangarei'),
('HPN', 'USA', 'White Plains (NY)'),
('YXY', 'Canada', 'Whitehorse'),
('HAP', 'Australia', 'Whitsunday Resort'),
('WYA', 'Australia', 'Whyalla'),
('SPS', 'USA', 'Wichita Falls (TX)'),
('ICT', 'USA', 'Wichita (KS)'),
('WIC', 'United Kingdom', 'Wick'),
('WHM', 'Australia', 'Wickham'),
('VIE', 'Austria', 'Wien (Vienna) - Vienna International'),
('WIE', 'Germany', 'Wiesbaden, Air Base'),
('AVP', 'USA', 'Wilkes Barre/Scranton (PA)'),
('IPT', 'USA', 'Williamsport (PA)'),
('ISL', 'USA', 'Williston (ND)'),
('ILM', 'USA', 'Wilmington (NC)'),
('VNO', 'Lithuania', 'Wilna (Vilnius)'),
('WUN', 'Australia', 'Wiluna'),
('ERS', 'Namibia', 'Windhoek - Eros'),
('WDH', 'Namibia', 'Windhoek - Hosea Kutako International'),
('YQG', 'Canada', 'Windsor Ontario'),
('YWG', 'Canada', 'Winnipeg International'),
('OLF', 'USA', 'Wolf Point (MT)'),
('WOL', 'Australia', 'Wollongong'),
('UMR', 'Australia', 'Woomera'),
('ORH', 'USA', 'Worcester (MA)'),
('WRL', 'USA', 'Worland (WY)'),
('WRG', 'USA', 'Wrangell (AK)'),
('WUH', 'Hubei, PR China', 'Wuhan'),
('WYN', 'Australia', 'Wyndham'),
('XMN', 'Fujian, PR China', 'Xiamen'),
('XIY', 'Shaanxi, PR China', 'Xi an - Xianyang'),
('YKM', 'USA', 'Yakima (WA)'),
('YAK', 'USA', 'Yakutat (AK)'),
('YKS', 'Russia', 'Yakutsk'),
('GAJ', 'Japan', 'Yamagata, Junmachi'),
('ASK', 'Côte d Ivoire', 'Yamoussoukro'),
('YNB', 'Saudi Arabia', 'Yanbu'),
('RGN', 'Myanmar', 'Yangon (Rangoon) - Mingaladon'),
('YAO', 'Cameroon', 'Yaounde'),
('YZF', 'Canada', 'Yellowknife'),
('SVX', 'Russia', 'Yekaterinburg - Koltsovo Airport'),
('YIH', 'Hubei, PR China', 'Yichang'),
('YOK', 'Japan', 'Yokohama'),
('YUM', 'USA', 'Yuma (AZ)'),
('ZCL', 'Mexico', 'Zacatecas'),
('ZAD', 'Croatia (Hrvatska)', 'Zadar'),
('ZAG', 'Croatia (Hrvatska)', 'Zagreb - Zagreb Airport Pleso'),
('ZTH', 'Greece', 'Zakynthos'),
('ZAZ', 'Spain', 'Zaragoza'),
('PZH', 'Pakistan', 'Zhob'),
('ZND', 'Niger', 'Zinder'),
('OUZ', 'Mauritania', 'Zouerate'),
('ZRH', 'Switzerland', 'Zurich (Zürich) - Kloten');
