package porodica;
import com.ftn.sbnz.backward.model.models.Woman;
import com.ftn.sbnz.backward.model.models.Man;
import com.ftn.sbnz.backward.model.models.Parent;

rule "get women"
agenda-group "women"
when
    $w: Woman()
then
    System.out.println($w.getName());
end

rule "get men"
agenda-group "men"
when
    $w: Man()
then
    System.out.println($w.getName());
end

rule "get father"
agenda-group "father"
when
    $m: Man()
    $p: Parent(parent == $m.name, $c: child)
then
    System.out.println($m.getName() + " " + $c);
end

rule "get mother"
agenda-group "mother"
when
    $m: Woman()
    $p: Parent(parent == $m.name, $c: child)
then
    System.out.println($m.getName() + " " + $c);
end

rule "get son"
agenda-group "son"
when
    $m: Man()
    $p: Parent($parent: parent, child == $m.name)
then
    System.out.println($parent + " " + $m.getName());
end

rule "get daughter"
agenda-group "daughter"
when
    $m: Woman()
    $p: Parent($parent: parent, child == $m.name)
then
    System.out.println($parent + " " + $m.getName());
end

rule "get siblings"
agenda-group "siblings"
when
    Parent($p1: parent, $c1: child)
    Parent($p1 == parent, $c2: child, $c2 != $c1)

then
    System.out.println($c1 + " " + $c2);
end

rule "get fullsiblings"
agenda-group "fullsiblings"
when
    Parent($p1: parent, $c1: child)
    Parent($p1 == parent, $c2: child, $c2 != $c1)
    Parent($p2: parent, $c1 == child, $p1!=$p2)
    Parent($p2 == parent, $c2 == child)
then
    System.out.println($c1 + " " + $c2);
end

rule "get uncles"
agenda-group "uncle"
when
    $m: Man()
    Parent($p1: parent, $m.name == child)
    Parent($p1 == parent, $sibling: child, $sibling!=$m.name)
    Parent($sibling == parent, $result: child)
then
    System.out.println($m.getName() + " " + $result);
end


rule "get aunts"
agenda-group "aunt"
when
    $m: Woman()
    Parent($p1: parent, $m.name == child)
    Parent($p1 == parent, $sibling: child, $sibling!=$m.name)
    Parent($sibling == parent, $result: child)
then
    System.out.println($m.getName() + " " + $result);
end


rule "get grandparents"
agenda-group "grandparents"
when
    Parent($gp: parent, $p: child)
    Parent($p == parent, $c: child)
then
    System.out.println($gp + " " + $c);
end
