package com.ftn.sbnz.model.enums;

public enum NotificationType {
    SPLIT_FARE, ACCEPTED_RIDE, CAR_TECHNICAL_PROBLEM, EVERYONE_PAYED, DID_NOT_APPEAR, REMINDER, CAR_REACHED_DESTINATION, CAR_POSITION, DRIVER_INCONSISTENCY, RIDE_DENIED
}
